<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyCreditRateTiersItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyCreditRateTiersItem', 'required' => ['min_quantity', 'max_quantity', 'unit_price'], 'properties' => ['min_quantity' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1], 'max_quantity' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'unit_price' => ['kind' => 'primitive', 'type' => 'string']], 'additionalProperties' => true];

    public function __construct(
        public int $minQuantity,
        public ?int $maxQuantity,
        /** Unit price per credit in major currency units. Fractional unit prices are supported. */
        public string $unitPrice,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            minQuantity: $data['min_quantity'],
            maxQuantity: $data['max_quantity'] ?? null,
            unitPrice: $data['unit_price'],
            additionalProperties: SchemaValidator::unknownFields($data, ['min_quantity', 'max_quantity', 'unit_price']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'min_quantity' => $this->minQuantity,
            'max_quantity' => $this->maxQuantity,
            'unit_price' => $this->unitPrice,
        ], ['min_quantity', 'max_quantity', 'unit_price'], $this->presentFields));
    }
}
