<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatus implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatus', 'required' => ['history', 'status'], 'properties' => ['history' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'string']], 'status' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus']], 'additionalProperties' => true];

    public function __construct(
        /** @var array<string> */
        public array $history,
        public CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus $status,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            history: $data['history'],
            status: CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus::fromArray($data['status']),
            additionalProperties: SchemaValidator::unknownFields($data, ['history', 'status']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'history' => $this->history,
            'status' => $this->status->toArray(),
        ], ['history', 'status'], $this->presentFields));
    }
}
