<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundStatus: string
{
    case Pending = 'pending';
    case Effective = 'effective';
    case Failed = 'failed';
    case Cancelled = 'cancelled';
}
