<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes: string
{
    case Downloadable = 'DOWNLOADABLE';
    case Text = 'TEXT';
    case Dynamic = 'DYNAMIC';
    case Manual = 'MANUAL';
    case LicenseKey = 'LICENSE_KEY';
    case Bundle = 'BUNDLE';
    case Booking = 'BOOKING';
    case Credits = 'CREDITS';
}
