<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItem', 'required' => ['path', 'metadata'], 'properties' => ['path' => ['kind' => 'primitive', 'type' => 'string'], 'metadata' => ['kind' => 'model', 'class' => 'CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItemPropertyMetadata']], 'additionalProperties' => true];

    public function __construct(
        public string $path,
        public CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItemPropertyMetadata $metadata,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            path: $data['path'],
            metadata: CreateProductResponseValue201ApplicationJsonPropertyDataPropertyImagesItemPropertyMetadata::fromArray($data['metadata']),
            additionalProperties: SchemaValidator::unknownFields($data, ['path', 'metadata']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'path' => $this->path,
            'metadata' => $this->metadata->toArray(),
        ], ['path', 'metadata'], $this->presentFields));
    }
}
