<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPayment implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPayment', 'required' => ['fee', 'gateway', 'subtotal', 'expires_at', 'full_price', 'original_amount'], 'properties' => ['fee' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee'], 'gateway' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway'], 'subtotal' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal'], 'expires_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time'], 'full_price' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice'], 'original_amount' => ['kind' => 'model', 'class' => 'CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount']], 'additionalProperties' => true];

    public function __construct(
        public CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee $fee,
        public CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway $gateway,
        public CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal $subtotal,
        public \DateTimeImmutable $expiresAt,
        public CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice $fullPrice,
        public CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount $originalAmount,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            fee: CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee::fromArray($data['fee']),
            gateway: CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway::fromArray($data['gateway']),
            subtotal: CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal::fromArray($data['subtotal']),
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            fullPrice: CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice::fromArray($data['full_price']),
            originalAmount: CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount::fromArray($data['original_amount']),
            additionalProperties: SchemaValidator::unknownFields($data, ['fee', 'gateway', 'subtotal', 'expires_at', 'full_price', 'original_amount']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'fee' => $this->fee->toArray(),
            'gateway' => $this->gateway->toArray(),
            'subtotal' => $this->subtotal->toArray(),
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'full_price' => $this->fullPrice->toArray(),
            'original_amount' => $this->originalAmount->toArray(),
        ], ['fee', 'gateway', 'subtotal', 'expires_at', 'full_price', 'original_amount'], $this->presentFields));
    }
}
