<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class CreateCustomerSessionResponseValue201ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'CreateCustomerSessionResponseValue201ApplicationJsonPropertyData', 'required' => ['id', 'token', 'redemption_url', 'expires_at'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uuid'], 'token' => ['kind' => 'primitive', 'type' => 'string'], 'redemption_url' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uri'], 'expires_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public string $id,
        public string $token,
        public string $redemptionUrl,
        public \DateTimeImmutable $expiresAt,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            token: $data['token'],
            redemptionUrl: $data['redemption_url'],
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'token', 'redemption_url', 'expires_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'token' => $this->token,
            'redemption_url' => $this->redemptionUrl,
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'token', 'redemption_url', 'expires_at'], $this->presentFields));
    }
}
