<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

/** The customer's purchase summary. Seller-only payment details and status timelines are not included. */
readonly class CustomerPortalOrder implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'CustomerPortalOrder', 'required' => ['id', 'status', 'currency', 'subtotal_cents', 'total_cents', 'line_items', 'created_at', 'updated_at'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'status' => ['kind' => 'primitive', 'type' => 'string'], 'currency' => ['kind' => 'primitive', 'type' => 'string'], 'subtotal_cents' => ['kind' => 'primitive', 'type' => 'integer'], 'total_cents' => ['kind' => 'primitive', 'type' => 'integer'], 'line_items' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'CustomerPortalOrderLineItem']], 'created_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'updated_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']]], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $status,
        /** Uppercase currency code for the order amounts. */
        public string $currency,
        /** Order subtotal in minor currency units; 1999 means USD 19.99 when currency is USD. */
        public int $subtotalCents,
        /** Order total including tax, in minor currency units. */
        public int $totalCents,
        /** @var array<\SellApp\Resource\CustomerPortalOrderLineItem> */
        public array $lineItems,
        public ?\DateTimeImmutable $createdAt,
        public ?\DateTimeImmutable $updatedAt,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            status: $data['status'],
            currency: $data['currency'],
            subtotalCents: $data['subtotal_cents'],
            totalCents: $data['total_cents'],
            lineItems: array_map(fn ($item) => CustomerPortalOrderLineItem::fromArray($item), $data['line_items']),
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'status', 'currency', 'subtotal_cents', 'total_cents', 'line_items', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'status' => $this->status,
            'currency' => $this->currency,
            'subtotal_cents' => $this->subtotalCents,
            'total_cents' => $this->totalCents,
            'line_items' => array_map(fn ($item) => $item->toArray(), $this->lineItems),
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'status', 'currency', 'subtotal_cents', 'total_cents', 'line_items', 'created_at', 'updated_at'], $this->presentFields));
    }
}
