<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class DeleteCourseSectionResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'DeleteCourseSectionResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'title', 'description', 'sort_order', 'lessons', 'created_at', 'updated_at'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'title' => ['kind' => 'primitive', 'type' => 'string'], 'description' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'sort_order' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1], 'lessons' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'DeleteCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItem']], 'created_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time'], 'updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $title,
        public ?string $description,
        public int $sortOrder,
        /** @var array<\SellApp\Resource\DeleteCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItem> */
        public array $lessons,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            title: $data['title'],
            description: $data['description'] ?? null,
            sortOrder: $data['sort_order'],
            lessons: array_map(fn ($item) => DeleteCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItem::fromArray($item), $data['lessons']),
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'title', 'description', 'sort_order', 'lessons', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'title' => $this->title,
            'description' => $this->description,
            'sort_order' => $this->sortOrder,
            'lessons' => array_map(fn ($item) => $item->toArray(), $this->lessons),
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'title', 'description', 'sort_order', 'lessons', 'created_at', 'updated_at'], $this->presentFields));
    }
}
