<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum Event: string
{
    case BookingCancelled = 'booking.cancelled';
    case BookingRescheduled = 'booking.rescheduled';
    case CashAppPaymentRequiresAttention = 'cash_app.payment_requires_attention';
    case ChargeCompleted = 'charge.completed';
    case ChargeCreated = 'charge.created';
    case ChargeDisputed = 'charge.disputed';
    case ChargePartialPaid = 'charge.partial_paid';
    case ChargeReview = 'charge.review';
    case FeedbackCreated = 'feedback.created';
    case OrderCompleted = 'order.completed';
    case OrderCreated = 'order.created';
    case OrderDisputed = 'order.disputed';
    case OrderManualPaymentCompleted = 'order.manual_payment_completed';
    case OrderPaid = 'order.paid';
    case OrderPartialPaid = 'order.partial_paid';
    case ProductCreated = 'product.created';
    case ProductTrashed = 'product.trashed';
    case ProductUpdated = 'product.updated';
    case SubscriptionCancelled = 'subscription.cancelled';
    case SubscriptionCreated = 'subscription.created';
    case SubscriptionRenewed = 'subscription.renewed';
    case TicketMessageCreated = 'ticket_message.created';
    case VariantCreated = 'variant.created';
    case VariantSoldOut = 'variant.sold_out';
    case VariantUpdated = 'variant.updated';
}
