<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus: string
{
    case Pending = 'pending';
    case Confirmed = 'confirmed';
    case Cancelled = 'cancelled';
    case NeedsReschedule = 'needs_reschedule';
    case Failed = 'failed';
}
