<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus: string
{
    case Pending = 'pending';
    case Synced = 'synced';
    case Skipped = 'skipped';
    case Cancelled = 'cancelled';
    case Failed = 'failed';
}
