<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetAccountResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetAccountResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'username', 'email', 'credential_type'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'string'], 'username' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'email' => ['kind' => 'primitive', 'type' => 'string'], 'credential_type' => ['kind' => 'enum', 'values' => ['sanctum', 'oauth']]], 'additionalProperties' => true];

    public function __construct(
        public string $id,
        public ?string $username,
        public string $email,
        public GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType|string $credentialType,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            username: $data['username'] ?? null,
            email: $data['email'],
            credentialType: GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType::tryFrom($data['credential_type']) ?? $data['credential_type'],
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'username', 'email', 'credential_type']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'username' => $this->username,
            'email' => $this->email,
            'credential_type' => $this->credentialType instanceof \BackedEnum ? $this->credentialType->value : $this->credentialType,
        ], ['id', 'username', 'email', 'credential_type'], $this->presentFields));
    }
}
