<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetCreditBalanceResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetCreditBalanceResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'store_id', 'customer_id', 'product_id', 'balance_units'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'store_id' => ['kind' => 'primitive', 'type' => 'integer'], 'customer_id' => ['kind' => 'primitive', 'type' => 'integer'], 'product_id' => ['kind' => 'primitive', 'type' => 'integer'], 'balance_units' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0], 'customer_email' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'email']], 'product_title' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'ledger_entries' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'GetCreditBalanceResponseValue200ApplicationJsonPropertyDataPropertyLedgerEntriesItem']], 'created_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time'], 'updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public int $storeId,
        public int $customerId,
        public int $productId,
        public int $balanceUnits,
        /** The email of the customer holding the balance, or null once the customer is deleted. */
        public ?string $customerEmail = null,
        /** The title of the credits product, or null once the product is soft-deleted. */
        public ?string $productTitle = null,
        /** @var array<\SellApp\Resource\GetCreditBalanceResponseValue200ApplicationJsonPropertyDataPropertyLedgerEntriesItem>|null */
        public ?array $ledgerEntries = null,
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $updatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            storeId: $data['store_id'],
            customerId: $data['customer_id'],
            productId: $data['product_id'],
            balanceUnits: $data['balance_units'],
            customerEmail: $data['customer_email'] ?? null,
            productTitle: $data['product_title'] ?? null,
            ledgerEntries: isset($data['ledger_entries']) ? array_map(fn ($item) => GetCreditBalanceResponseValue200ApplicationJsonPropertyDataPropertyLedgerEntriesItem::fromArray($item), $data['ledger_entries']) : null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'store_id', 'customer_id', 'product_id', 'balance_units', 'customer_email', 'product_title', 'ledger_entries', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'store_id' => $this->storeId,
            'customer_id' => $this->customerId,
            'product_id' => $this->productId,
            'balance_units' => $this->balanceUnits,
            'customer_email' => $this->customerEmail,
            'product_title' => $this->productTitle,
            'ledger_entries' => $this->ledgerEntries !== null ? array_map(fn ($item) => $item->toArray(), $this->ledgerEntries) : null,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'store_id', 'customer_id', 'product_id', 'balance_units'], $this->presentFields));
    }
}
