<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetDisputeResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetDisputeResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'source', 'provider', 'amount', 'currency', 'status'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uuid'], 'source' => ['kind' => 'model', 'class' => 'GetDisputeResponseValue200ApplicationJsonPropertyDataPropertySource'], 'provider' => ['kind' => 'primitive', 'type' => 'string'], 'amount' => ['kind' => 'primitive', 'type' => 'integer'], 'currency' => ['kind' => 'primitive', 'type' => 'string'], 'status' => ['kind' => 'enum', 'values' => ['open', 'under_review', 'won', 'lost', 'closed']], 'provider_dispute_id' => ['kind' => 'primitive', 'type' => 'string'], 'reason' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']]], 'additionalProperties' => true];

    public function __construct(
        public string $id,
        public GetDisputeResponseValue200ApplicationJsonPropertyDataPropertySource $source,
        public string $provider,
        public int $amount,
        public string $currency,
        public GetDisputeResponseValue200ApplicationJsonPropertyDataStatus|string $status,
        public ?string $providerDisputeId = null,
        public ?string $reason = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            source: GetDisputeResponseValue200ApplicationJsonPropertyDataPropertySource::fromArray($data['source']),
            provider: $data['provider'],
            amount: $data['amount'],
            currency: $data['currency'],
            status: GetDisputeResponseValue200ApplicationJsonPropertyDataStatus::tryFrom($data['status']) ?? $data['status'],
            providerDisputeId: $data['provider_dispute_id'] ?? null,
            reason: $data['reason'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'source', 'provider', 'amount', 'currency', 'status', 'provider_dispute_id', 'reason']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'source' => $this->source->toArray(),
            'provider' => $this->provider,
            'amount' => $this->amount,
            'currency' => $this->currency,
            'status' => $this->status instanceof \BackedEnum ? $this->status->value : $this->status,
            'provider_dispute_id' => $this->providerDisputeId,
            'reason' => $this->reason,
        ], ['id', 'source', 'provider', 'amount', 'currency', 'status'], $this->presentFields));
    }
}
