<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatus implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatus', 'required' => ['history', 'status'], 'properties' => ['history' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem']], 'status' => ['kind' => 'model', 'class' => 'GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyStatus']], 'additionalProperties' => true];

    public function __construct(
        /** @var array<\SellApp\Resource\GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem> */
        public array $history,
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyStatus $status,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            history: array_map(fn ($item) => GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem::fromArray($item), $data['history']),
            status: GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyStatusPropertyStatus::fromArray($data['status']),
            additionalProperties: SchemaValidator::unknownFields($data, ['history', 'status']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'history' => array_map(fn ($item) => $item->toArray(), $this->history),
            'status' => $this->status->toArray(),
        ], ['history', 'status'], $this->presentFields));
    }
}
