<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetRewardCouponTemplateResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetRewardCouponTemplateResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'name', 'type', 'discount', 'store_wide', 'redemption_mode', 'is_active'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'name' => ['kind' => 'primitive', 'type' => 'string'], 'type' => ['kind' => 'enum', 'values' => ['PERCENTAGE', 'AMOUNT']], 'discount' => ['kind' => 'primitive', 'type' => 'string'], 'store_wide' => ['kind' => 'primitive', 'type' => 'boolean'], 'redemption_mode' => ['kind' => 'enum', 'values' => ['customer_locked', 'shareable_once']], 'is_active' => ['kind' => 'primitive', 'type' => 'boolean'], 'minimum_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'maximum_discount_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'expires_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'expires_after_days' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'listing_ids' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer']], 'created_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'updated_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']]], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $name,
        public SdkCreateCouponRequestApplicationJsonType|string $type,
        public string $discount,
        public bool $storeWide,
        public SdkCreateRewardCouponTemplateRequestApplicationJsonRedemptionMode|string $redemptionMode,
        public bool $isActive,
        public ?string $minimumAmount = null,
        public ?string $maximumDiscountAmount = null,
        public ?\DateTimeImmutable $expiresAt = null,
        public ?int $expiresAfterDays = null,
        /** @var array<int>|null */
        public ?array $listingIds = null,
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $updatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            name: $data['name'],
            type: SdkCreateCouponRequestApplicationJsonType::tryFrom($data['type']) ?? $data['type'],
            discount: $data['discount'],
            storeWide: $data['store_wide'],
            redemptionMode: SdkCreateRewardCouponTemplateRequestApplicationJsonRedemptionMode::tryFrom($data['redemption_mode']) ?? $data['redemption_mode'],
            isActive: $data['is_active'],
            minimumAmount: $data['minimum_amount'] ?? null,
            maximumDiscountAmount: $data['maximum_discount_amount'] ?? null,
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
            expiresAfterDays: $data['expires_after_days'] ?? null,
            listingIds: $data['listing_ids'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'name', 'type', 'discount', 'store_wide', 'redemption_mode', 'is_active', 'minimum_amount', 'maximum_discount_amount', 'expires_at', 'expires_after_days', 'listing_ids', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'name' => $this->name,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'discount' => $this->discount,
            'store_wide' => $this->storeWide,
            'redemption_mode' => $this->redemptionMode instanceof \BackedEnum ? $this->redemptionMode->value : $this->redemptionMode,
            'is_active' => $this->isActive,
            'minimum_amount' => $this->minimumAmount,
            'maximum_discount_amount' => $this->maximumDiscountAmount,
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'expires_after_days' => $this->expiresAfterDays,
            'listing_ids' => $this->listingIds,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'name', 'type', 'discount', 'store_wide', 'redemption_mode', 'is_active'], $this->presentFields));
    }
}
