<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer', 'required' => ['id', 'email'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'email' => ['kind' => 'primitive', 'type' => 'string']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $email,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            email: $data['email'],
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'email']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'email' => $this->email,
        ], ['id', 'email'], $this->presentFields));
    }
}
