<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum InvoicesSearchBy: string
{
    case Default = 'default';
    case TransactionId = 'transaction_id';
    case SerialCode = 'serial_code';
    case AdditionalInfo = 'additional_info';
    case ProductName = 'product_name';
    case DiscordData = 'discord_data';
    case CryptoTxid = 'crypto_txid';
    case CryptoAddress = 'crypto_address';
    case CouponCode = 'coupon_code';
}
