<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

trait JsonSerializableTrait
{
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
