<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon', 'required' => ['id', 'code'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'code' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']]], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public ?string $code,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            code: $data['code'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'code']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'code' => $this->code,
        ], ['id', 'code'], $this->presentFields));
    }
}
