<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ListRefundsResponseValue200ApplicationJsonPropertyDataItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ListRefundsResponseValue200ApplicationJsonPropertyDataItem', 'required' => ['id', 'source', 'refundable', 'provider', 'amount_cents', 'currency', 'status'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'source' => ['kind' => 'primitive', 'type' => 'string'], 'refundable' => ['kind' => 'model', 'class' => 'ListRefundsResponseValue200ApplicationJsonPropertyDataItemPropertyRefundable'], 'provider' => ['kind' => 'primitive', 'type' => 'string'], 'amount_cents' => ['kind' => 'primitive', 'type' => 'integer'], 'currency' => ['kind' => 'primitive', 'type' => 'string'], 'status' => ['kind' => 'primitive', 'type' => 'string'], 'provider_payment_id' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'provider_refund_id' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'reason' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']]], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $source,
        public ListRefundsResponseValue200ApplicationJsonPropertyDataItemPropertyRefundable $refundable,
        public string $provider,
        public int $amountCents,
        public string $currency,
        public string $status,
        public ?string $providerPaymentId = null,
        public ?string $providerRefundId = null,
        public ?string $reason = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            source: $data['source'],
            refundable: ListRefundsResponseValue200ApplicationJsonPropertyDataItemPropertyRefundable::fromArray($data['refundable']),
            provider: $data['provider'],
            amountCents: $data['amount_cents'],
            currency: $data['currency'],
            status: $data['status'],
            providerPaymentId: $data['provider_payment_id'] ?? null,
            providerRefundId: $data['provider_refund_id'] ?? null,
            reason: $data['reason'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'source', 'refundable', 'provider', 'amount_cents', 'currency', 'status', 'provider_payment_id', 'provider_refund_id', 'reason']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'source' => $this->source,
            'refundable' => $this->refundable->toArray(),
            'provider' => $this->provider,
            'amount_cents' => $this->amountCents,
            'currency' => $this->currency,
            'status' => $this->status,
            'provider_payment_id' => $this->providerPaymentId,
            'provider_refund_id' => $this->providerRefundId,
            'reason' => $this->reason,
        ], ['id', 'source', 'refundable', 'provider', 'amount_cents', 'currency', 'status'], $this->presentFields));
    }
}
