<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemHealthStatus: string
{
    case Disconnected = 'disconnected';
    case Healthy = 'healthy';
    case AttentionRequired = 'attention_required';
}
