<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmount implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmount', 'required' => ['base', 'currency', 'units', 'vat', 'total'], 'properties' => ['base' => ['kind' => 'primitive', 'type' => 'string'], 'currency' => ['kind' => 'primitive', 'type' => 'string'], 'units' => ['kind' => 'primitive', 'type' => 'integer'], 'vat' => ['kind' => 'primitive', 'type' => 'integer'], 'total' => ['kind' => 'model', 'class' => 'ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmountPropertyTotal']], 'additionalProperties' => true];

    public function __construct(
        public string $base,
        public string $currency,
        public int $units,
        public int $vat,
        public ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmountPropertyTotal $total,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            base: $data['base'],
            currency: $data['currency'],
            units: $data['units'],
            vat: $data['vat'],
            total: ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmountPropertyTotal::fromArray($data['total']),
            additionalProperties: SchemaValidator::unknownFields($data, ['base', 'currency', 'units', 'vat', 'total']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'base' => $this->base,
            'currency' => $this->currency,
            'units' => $this->units,
            'vat' => $this->vat,
            'total' => $this->total->toArray(),
        ], ['base', 'currency', 'units', 'vat', 'total'], $this->presentFields));
    }
}
