<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class PaginationLinks implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'PaginationLinks', 'required' => ['first', 'last', 'prev', 'next'], 'properties' => ['first' => ['kind' => 'primitive', 'type' => 'string'], 'last' => ['kind' => 'primitive', 'type' => 'string'], 'prev' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'next' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']]], 'additionalProperties' => true];

    public function __construct(
        public string $first,
        public string $last,
        public ?string $prev,
        public ?string $next,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            first: $data['first'],
            last: $data['last'],
            prev: $data['prev'] ?? null,
            next: $data['next'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['first', 'last', 'prev', 'next']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'first' => $this->first,
            'last' => $this->last,
            'prev' => $this->prev,
            'next' => $this->next,
        ], ['first', 'last', 'prev', 'next'], $this->presentFields));
    }
}
