<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class QueueVariantSerialImportResponseValue202ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'QueueVariantSerialImportResponseValue202ApplicationJsonPropertyData', 'required' => ['status', 'tracker_id'], 'properties' => ['status' => ['kind' => 'literal', 'value' => 'queued'], 'tracker_id' => ['kind' => 'primitive', 'type' => 'string']], 'additionalProperties' => true];

    public function __construct(
        public string $status,
        public string $trackerId,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            status: $data['status'] ?? 'queued',
            trackerId: $data['tracker_id'],
            additionalProperties: SchemaValidator::unknownFields($data, ['status', 'tracker_id']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'status' => $this->status,
            'tracker_id' => $this->trackerId,
        ], ['status', 'tracker_id'], $this->presentFields));
    }
}
