<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ReplaceProductRequestApplicationJsonPropertyOtherSettings implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ReplaceProductRequestApplicationJsonPropertyOtherSettings', 'required' => [], 'properties' => ['redirect_url' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uri'], 'video_url' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uri'], 'product_title' => ['kind' => 'primitive', 'type' => 'string'], 'product_description' => ['kind' => 'primitive', 'type' => 'string'], 'faq' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'ProductFaqInput']]], 'additionalProperties' => true];

    public function __construct(
        public ?string $redirectUrl = null,
        public ?string $videoUrl = null,
        public ?string $productTitle = null,
        public ?string $productDescription = null,
        /** @var array<\SellApp\Resource\ProductFaqInput>|null */
        public ?array $faq = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            redirectUrl: $data['redirect_url'] ?? null,
            videoUrl: $data['video_url'] ?? null,
            productTitle: $data['product_title'] ?? null,
            productDescription: $data['product_description'] ?? null,
            faq: isset($data['faq']) ? array_map(fn ($item) => ProductFaqInput::fromArray($item), $data['faq']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['redirect_url', 'video_url', 'product_title', 'product_description', 'faq']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'redirect_url' => $this->redirectUrl,
            'video_url' => $this->videoUrl,
            'product_title' => $this->productTitle,
            'product_description' => $this->productDescription,
            'faq' => $this->faq !== null ? array_map(fn ($item) => $item->toArray(), $this->faq) : null,
        ], [], $this->presentFields));
    }
}
