<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketing implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketing', 'required' => [], 'properties' => ['abandoned_cart' => ['kind' => 'model', 'class' => 'ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketingPropertyAbandonedCart']], 'additionalProperties' => true];

    public function __construct(
        public ?ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketingPropertyAbandonedCart $abandonedCart = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            abandonedCart: isset($data['abandoned_cart']) ? ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketingPropertyAbandonedCart::fromArray($data['abandoned_cart']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['abandoned_cart']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'abandoned_cart' => $this->abandonedCart?->toArray(),
        ], [], $this->presentFields));
    }
}
