<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ReplaceProductVariantWithPutRequestApplicationJsonPropertyBulkDiscountItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ReplaceProductVariantWithPutRequestApplicationJsonPropertyBulkDiscountItem', 'required' => ['minimum_purchase_amount', 'discount_percentage'], 'properties' => ['minimum_purchase_amount' => ['kind' => 'primitive', 'type' => 'integer'], 'discount_percentage' => ['kind' => 'primitive', 'type' => 'integer']], 'additionalProperties' => true];

    public function __construct(
        public int $minimumPurchaseAmount,
        public int $discountPercentage,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            minimumPurchaseAmount: $data['minimum_purchase_amount'],
            discountPercentage: $data['discount_percentage'],
            additionalProperties: SchemaValidator::unknownFields($data, ['minimum_purchase_amount', 'discount_percentage']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'minimum_purchase_amount' => $this->minimumPurchaseAmount,
            'discount_percentage' => $this->discountPercentage,
        ], ['minimum_purchase_amount', 'discount_percentage'], $this->presentFields));
    }
}
