<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class RestorePromotionRequestApplicationJsonPropertyPhasesItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'RestorePromotionRequestApplicationJsonPropertyPhasesItem', 'required' => ['discount_type', 'discount_value'], 'properties' => ['discount_type' => ['kind' => 'enum', 'values' => ['percentage', 'fixed']], 'discount_value' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'number', 'minimum' => 1, 'maxLength' => 255], ['kind' => 'primitive', 'type' => 'string', 'minimum' => 1, 'maxLength' => 255]]], 'ends_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'max_redemptions' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1, 'maximum' => 4294967295]], 'minimum_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'number', 'minimum' => 1, 'maxLength' => 255], ['kind' => 'primitive', 'type' => 'string', 'minimum' => 1, 'maxLength' => 255]]]]], 'additionalProperties' => true];

    public function __construct(
        public CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType|string $discountType,
        /** Percentage from 1 through 100, or a fixed decimal amount of at least 1. */
        public float|string $discountValue,
        /** A future date and time, or null for no time limit. */
        public ?\DateTimeImmutable $endsAt = null,
        public ?int $maxRedemptions = null,
        public float|string|null $minimumAmount = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            discountType: CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType::tryFrom($data['discount_type']) ?? $data['discount_type'],
            discountValue: $data['discount_value'],
            endsAt: isset($data['ends_at']) ? new \DateTimeImmutable($data['ends_at']) : null,
            maxRedemptions: $data['max_redemptions'] ?? null,
            minimumAmount: $data['minimum_amount'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['discount_type', 'discount_value', 'ends_at', 'max_redemptions', 'minimum_amount']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'discount_type' => $this->discountType instanceof \BackedEnum ? $this->discountType->value : $this->discountType,
            'discount_value' => $this->discountValue,
            'ends_at' => $this->endsAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'max_redemptions' => $this->maxRedemptions,
            'minimum_amount' => $this->minimumAmount,
        ], ['discount_type', 'discount_value'], $this->presentFields));
    }
}
