<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkAttachBundleItemsResponseValue200ApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkAttachBundleItemsResponseValue200ApplicationJson', 'required' => ['attached'], 'properties' => ['attached' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer']]], 'additionalProperties' => true];

    public function __construct(
        /** @var array<int> */
        public array $attached,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            attached: $data['attached'],
            additionalProperties: SchemaValidator::unknownFields($data, ['attached']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'attached' => $this->attached,
        ], ['attached'], $this->presentFields));
    }
}
