<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkBatchCreateProductVariantsRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkBatchCreateProductVariantsRequestApplicationJson', 'required' => ['resources'], 'properties' => ['resources' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem']]], 'additionalProperties' => true];

    public function __construct(
        /** @var array<\SellApp\Resource\BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem> */
        public array $resources,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            resources: array_map(fn ($item) => BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem::fromArray($item), $data['resources']),
            additionalProperties: SchemaValidator::unknownFields($data, ['resources']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'resources' => array_map(fn ($item) => $item->toArray(), $this->resources),
        ], ['resources'], $this->presentFields));
    }
}
