<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkCreateCourseLessonRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkCreateCourseLessonRequestApplicationJson', 'required' => ['title', 'type'], 'properties' => ['title' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255], 'type' => ['kind' => 'enum', 'values' => ['lecture', 'video', 'text', 'quiz', 'assignment']], 'content' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'is_preview' => ['kind' => 'primitive', 'type' => 'boolean'], 'is_published' => ['kind' => 'primitive', 'type' => 'boolean'], 'assignment' => ['kind' => 'model', 'class' => 'CreateCourseLessonRequestApplicationJsonPropertyAssignment'], 'questions' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem'], 'maxItems' => 12], 'expected_updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public string $title,
        public SdkCreateCourseLessonRequestApplicationJsonType|string $type,
        public ?string $content = null,
        /** Preview is available only for video lessons. */
        public ?bool $isPreview = null,
        public ?bool $isPublished = null,
        public ?CreateCourseLessonRequestApplicationJsonPropertyAssignment $assignment = null,
        /** @var array<\SellApp\Resource\CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem>|null */
        public ?array $questions = null,
        public ?\DateTimeImmutable $expectedUpdatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            title: $data['title'],
            type: SdkCreateCourseLessonRequestApplicationJsonType::tryFrom($data['type']) ?? $data['type'],
            content: $data['content'] ?? null,
            isPreview: $data['is_preview'] ?? null,
            isPublished: $data['is_published'] ?? null,
            assignment: isset($data['assignment']) ? CreateCourseLessonRequestApplicationJsonPropertyAssignment::fromArray($data['assignment']) : null,
            questions: isset($data['questions']) ? array_map(fn ($item) => CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem::fromArray($item), $data['questions']) : null,
            expectedUpdatedAt: isset($data['expected_updated_at']) ? new \DateTimeImmutable($data['expected_updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['title', 'type', 'content', 'is_preview', 'is_published', 'assignment', 'questions', 'expected_updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'title' => $this->title,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'content' => $this->content,
            'is_preview' => $this->isPreview,
            'is_published' => $this->isPublished,
            'assignment' => $this->assignment?->toArray(),
            'questions' => $this->questions !== null ? array_map(fn ($item) => $item->toArray(), $this->questions) : null,
            'expected_updated_at' => $this->expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['title', 'type'], $this->presentFields));
    }
}
