<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkConnectCustomDomainRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkConnectCustomDomainRequestApplicationJson', 'required' => ['domain'], 'properties' => ['domain' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 253]], 'additionalProperties' => true];

    public function __construct(
        /** The custom domain as a hostname or URL. */
        public string $domain,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            domain: $data['domain'],
            additionalProperties: SchemaValidator::unknownFields($data, ['domain']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'domain' => $this->domain,
        ], ['domain'], $this->presentFields));
    }
}
