<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkCreateRewardRuleRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkCreateRewardRuleRequestApplicationJson', 'required' => ['name', 'is_active', 'trigger_type', 'trigger_threshold', 'outputs'], 'properties' => ['name' => ['kind' => 'primitive', 'type' => 'string', 'minLength' => 1, 'maxLength' => 120], 'is_active' => ['kind' => 'primitive', 'type' => 'boolean'], 'trigger_type' => ['kind' => 'enum', 'values' => ['PURCHASE_COUNT', 'TOTAL_SPENT']], 'trigger_threshold' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1], 'outputs' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'CreateRewardRuleRequestApplicationJsonPropertyOutputsItem'], 'minItems' => 1], 'description' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255]], 'expected_updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public string $name,
        public bool $isActive,
        public SdkCreateRewardRuleRequestApplicationJsonTriggerType|string $triggerType,
        public int $triggerThreshold,
        /** @var array<\SellApp\Resource\CreateRewardRuleRequestApplicationJsonPropertyOutputsItem> */
        public array $outputs,
        public ?string $description = null,
        public ?\DateTimeImmutable $expectedUpdatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            name: $data['name'],
            isActive: $data['is_active'],
            triggerType: SdkCreateRewardRuleRequestApplicationJsonTriggerType::tryFrom($data['trigger_type']) ?? $data['trigger_type'],
            triggerThreshold: $data['trigger_threshold'],
            outputs: array_map(fn ($item) => CreateRewardRuleRequestApplicationJsonPropertyOutputsItem::fromArray($item), $data['outputs']),
            description: $data['description'] ?? null,
            expectedUpdatedAt: isset($data['expected_updated_at']) ? new \DateTimeImmutable($data['expected_updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['name', 'is_active', 'trigger_type', 'trigger_threshold', 'outputs', 'description', 'expected_updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'name' => $this->name,
            'is_active' => $this->isActive,
            'trigger_type' => $this->triggerType instanceof \BackedEnum ? $this->triggerType->value : $this->triggerType,
            'trigger_threshold' => $this->triggerThreshold,
            'outputs' => array_map(fn ($item) => $item->toArray(), $this->outputs),
            'description' => $this->description,
            'expected_updated_at' => $this->expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['name', 'is_active', 'trigger_type', 'trigger_threshold', 'outputs'], $this->presentFields));
    }
}
