<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum SdkCreateRewardRuleRequestApplicationJsonTriggerType: string
{
    case PurchaseCount = 'PURCHASE_COUNT';
    case TotalSpent = 'TOTAL_SPENT';
}
