<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkCreateAddOnDraftRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkCreateAddOnDraftRequestApplicationJson', 'required' => ['title', 'description', 'visibility'], 'properties' => ['title' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255], 'description' => ['kind' => 'primitive', 'type' => 'string', 'minLength' => 5, 'maxLength' => 5000], 'visibility' => ['kind' => 'enum', 'values' => ['PUBLIC', 'ON_HOLD', 'HIDDEN', 'PRIVATE']], 'slug' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255, 'pattern' => '^[a-z0-9]+(?:-[a-z0-9]+)*$'], 'is_draft' => ['kind' => 'primitive', 'type' => 'boolean'], 'parent_product_ids' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer'], 'uniqueItems' => true], 'variant' => ['kind' => 'model', 'class' => 'CreateAddOnDraftRequestApplicationJsonPropertyVariant']], 'additionalProperties' => true];

    public function __construct(
        /** Seller-facing title for the add-on. */
        public string $title,
        /** Description shown when the add-on is offered. */
        public string $description,
        public CatalogVisibility|string $visibility,
        /** Optional store-unique slug. When omitted during creation, SellApp generates one from the title. */
        public ?string $slug = null,
        /** Defaults to true on creation. Set false to publish. Publication requires exactly one published, fixed-price, single-payment variant; creation can include that variant in the same request. */
        public ?bool $isDraft = null,
        /**
         * Ordered IDs of same-store, non-subscription products, courses, or bookings to assign. Supplying the field replaces the complete assignment set.
         * @var array<int>|null
         */
        public ?array $parentProductIds = null,
        public ?CreateAddOnDraftRequestApplicationJsonPropertyVariant $variant = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            title: $data['title'],
            description: $data['description'],
            visibility: CatalogVisibility::tryFrom($data['visibility']) ?? $data['visibility'],
            slug: $data['slug'] ?? null,
            isDraft: $data['is_draft'] ?? null,
            parentProductIds: $data['parent_product_ids'] ?? null,
            variant: isset($data['variant']) ? CreateAddOnDraftRequestApplicationJsonPropertyVariant::fromArray($data['variant']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['title', 'description', 'visibility', 'slug', 'is_draft', 'parent_product_ids', 'variant']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'title' => $this->title,
            'description' => $this->description,
            'visibility' => $this->visibility instanceof \BackedEnum ? $this->visibility->value : $this->visibility,
            'slug' => $this->slug,
            'is_draft' => $this->isDraft,
            'parent_product_ids' => $this->parentProductIds,
            'variant' => $this->variant?->toArray(),
        ], ['title', 'description', 'visibility'], $this->presentFields));
    }
}
