<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkEnableOrDisablePaymentMethodRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkEnableOrDisablePaymentMethodRequestApplicationJson', 'required' => ['enabled'], 'properties' => ['enabled' => ['kind' => 'primitive', 'type' => 'boolean']], 'additionalProperties' => true];

    public function __construct(
        public bool $enabled,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            enabled: $data['enabled'],
            additionalProperties: SchemaValidator::unknownFields($data, ['enabled']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'enabled' => $this->enabled,
        ], ['enabled'], $this->presentFields));
    }
}
