<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkInviteAffiliateRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkInviteAffiliateRequestApplicationJson', 'required' => ['email'], 'properties' => ['email' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'email', 'maxLength' => 255]], 'additionalProperties' => true];

    public function __construct(
        public string $email,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            email: $data['email'],
            additionalProperties: SchemaValidator::unknownFields($data, ['email']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'email' => $this->email,
        ], ['email'], $this->presentFields));
    }
}
