<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkPreviewSubscriptionPlanChangeRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkPreviewSubscriptionPlanChangeRequestApplicationJson', 'required' => ['target_variant_id'], 'properties' => ['target_variant_id' => ['kind' => 'primitive', 'type' => 'integer'], 'idempotency_key' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 128]], 'effective_timing' => ['kind' => 'enum', 'values' => ['immediate', 'next_renewal']], 'proration_behavior' => ['kind' => 'enum', 'values' => ['invoice_now', 'credit_next_invoice', 'none', 'provider_default']], 'metadata' => ['kind' => 'model', 'class' => 'PreviewSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata']], 'additionalProperties' => true];

    public function __construct(
        public int $targetVariantId,
        /** Optional idempotency key. You may also send this as the Idempotency-Key header. */
        public ?string $idempotencyKey = null,
        public SdkPreviewSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming|string|null $effectiveTiming = null,
        public SdkPreviewSubscriptionPlanChangeRequestApplicationJsonProrationBehavior|string|null $prorationBehavior = null,
        public ?PreviewSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata $metadata = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            targetVariantId: $data['target_variant_id'],
            idempotencyKey: $data['idempotency_key'] ?? null,
            effectiveTiming: isset($data['effective_timing']) ? SdkPreviewSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming::tryFrom($data['effective_timing']) ?? $data['effective_timing'] : null,
            prorationBehavior: isset($data['proration_behavior']) ? SdkPreviewSubscriptionPlanChangeRequestApplicationJsonProrationBehavior::tryFrom($data['proration_behavior']) ?? $data['proration_behavior'] : null,
            metadata: isset($data['metadata']) ? PreviewSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata::fromArray($data['metadata']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['target_variant_id', 'idempotency_key', 'effective_timing', 'proration_behavior', 'metadata']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'target_variant_id' => $this->targetVariantId,
            'idempotency_key' => $this->idempotencyKey,
            'effective_timing' => $this->effectiveTiming instanceof \BackedEnum ? $this->effectiveTiming->value : $this->effectiveTiming,
            'proration_behavior' => $this->prorationBehavior instanceof \BackedEnum ? $this->prorationBehavior->value : $this->prorationBehavior,
            'metadata' => $this->metadata?->toArray(),
        ], ['target_variant_id'], $this->presentFields));
    }
}
