<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkPauseSubscriptionRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkPauseSubscriptionRequestApplicationJson', 'required' => [], 'properties' => ['idempotency_key' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 128]], 'resume_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'reason' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 500]]], 'additionalProperties' => true];

    public function __construct(
        /** Optional idempotency key. You may also send this as the Idempotency-Key header. */
        public ?string $idempotencyKey = null,
        /** Use a future date-time at execution time. Automatic resume dates are supported only for Stripe; the shown date is illustrative. */
        public ?\DateTimeImmutable $resumeAt = null,
        public ?string $reason = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            idempotencyKey: $data['idempotency_key'] ?? null,
            resumeAt: isset($data['resume_at']) ? new \DateTimeImmutable($data['resume_at']) : null,
            reason: $data['reason'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['idempotency_key', 'resume_at', 'reason']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'idempotency_key' => $this->idempotencyKey,
            'resume_at' => $this->resumeAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'reason' => $this->reason,
        ], [], $this->presentFields));
    }
}
