<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum SdkPreviewSubscriptionPlanChangeRequestApplicationJsonProrationBehavior: string
{
    case InvoiceNow = 'invoice_now';
    case CreditNextInvoice = 'credit_next_invoice';
    case None = 'none';
    case ProviderDefault = 'provider_default';
}
