<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkReplaceCourseResponseValue200ApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkReplaceCourseResponseValue200ApplicationJson', 'required' => ['data'], 'properties' => ['data' => ['kind' => 'model', 'class' => 'ReplaceCourseResponseValue200ApplicationJsonPropertyData']], 'additionalProperties' => true];

    public function __construct(
        public ReplaceCourseResponseValue200ApplicationJsonPropertyData $data,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            data: ReplaceCourseResponseValue200ApplicationJsonPropertyData::fromArray($data['data']),
            additionalProperties: SchemaValidator::unknownFields($data, ['data']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'data' => $this->data->toArray(),
        ], ['data'], $this->presentFields));
    }
}
