<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkReplaceVariantDeliverableFileSettingsRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkReplaceVariantDeliverableFileSettingsRequestApplicationJson', 'required' => [], 'properties' => ['custom_name' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'folder_id' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'watermark' => ['kind' => 'primitive', 'type' => 'boolean'], 'max_downloads' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'limit_to_purchase_ip' => ['kind' => 'primitive', 'type' => 'boolean']], 'additionalProperties' => true];

    public function __construct(
        public ?string $customName = null,
        public ?int $folderId = null,
        public ?bool $watermark = null,
        public ?int $maxDownloads = null,
        public ?bool $limitToPurchaseIp = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            customName: $data['custom_name'] ?? null,
            folderId: $data['folder_id'] ?? null,
            watermark: $data['watermark'] ?? null,
            maxDownloads: $data['max_downloads'] ?? null,
            limitToPurchaseIp: $data['limit_to_purchase_ip'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['custom_name', 'folder_id', 'watermark', 'max_downloads', 'limit_to_purchase_ip']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'custom_name' => $this->customName,
            'folder_id' => $this->folderId,
            'watermark' => $this->watermark,
            'max_downloads' => $this->maxDownloads,
            'limit_to_purchase_ip' => $this->limitToPurchaseIp,
        ], [], $this->presentFields));
    }
}
