<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencoded implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencoded', 'required' => ['token'], 'properties' => ['token' => ['kind' => 'primitive', 'type' => 'string'], 'client_id' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uuid'], 'client_secret' => ['kind' => 'primitive', 'type' => 'string'], 'token_type_hint' => ['kind' => 'enum', 'values' => ['access_token', 'refresh_token']]], 'additionalProperties' => true];

    public function __construct(
        public string $token,
        /** The configured official CLI public client ID. It identifies the registration, not the executable. */
        public ?string $clientId = null,
        /** Legacy SDK field retained for compatibility. Omit for the official CLI; it has no client secret. */
        public ?string $clientSecret = null,
        public SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint|string|null $tokenTypeHint = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            token: $data['token'],
            clientId: $data['client_id'] ?? null,
            clientSecret: $data['client_secret'] ?? null,
            tokenTypeHint: isset($data['token_type_hint']) ? SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint::tryFrom($data['token_type_hint']) ?? $data['token_type_hint'] : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['token', 'client_id', 'client_secret', 'token_type_hint']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'token' => $this->token,
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'token_type_hint' => $this->tokenTypeHint instanceof \BackedEnum ? $this->tokenTypeHint->value : $this->tokenTypeHint,
        ], ['token'], $this->presentFields));
    }
}
