<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkReplaceVariantDeliverableFolderSettingsRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkReplaceVariantDeliverableFolderSettingsRequestApplicationJson', 'required' => [], 'properties' => ['name' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255], 'description' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255]], 'parent_id' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'sort_order' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0]], 'additionalProperties' => true];

    public function __construct(
        public ?string $name = null,
        public ?string $description = null,
        public ?int $parentId = null,
        public ?int $sortOrder = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            name: $data['name'] ?? null,
            description: $data['description'] ?? null,
            parentId: $data['parent_id'] ?? null,
            sortOrder: $data['sort_order'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['name', 'description', 'parent_id', 'sort_order']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'name' => $this->name,
            'description' => $this->description,
            'parent_id' => $this->parentId,
            'sort_order' => $this->sortOrder,
        ], [], $this->presentFields));
    }
}
