<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkSearchCustomersRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkSearchCustomersRequestApplicationJson', 'required' => [], 'properties' => ['filters' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchCustomersRequestApplicationJsonPropertyFiltersItem']], 'sort' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchCustomersRequestApplicationJsonPropertySortItem']], 'search' => ['kind' => 'model', 'class' => 'SearchCustomersRequestApplicationJsonPropertySearch'], 'includes' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchCustomersRequestApplicationJsonPropertyIncludesItem'], 'maxItems' => 0]], 'additionalProperties' => true];

    public function __construct(
        /** @var array<\SellApp\Resource\SearchCustomersRequestApplicationJsonPropertyFiltersItem>|null */
        public ?array $filters = null,
        /** @var array<\SellApp\Resource\SearchCustomersRequestApplicationJsonPropertySortItem>|null */
        public ?array $sort = null,
        public ?SearchCustomersRequestApplicationJsonPropertySearch $search = null,
        /** @var array<\SellApp\Resource\SearchCustomersRequestApplicationJsonPropertyIncludesItem>|null */
        public ?array $includes = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            filters: isset($data['filters']) ? array_map(fn ($item) => SearchCustomersRequestApplicationJsonPropertyFiltersItem::fromArray($item), $data['filters']) : null,
            sort: isset($data['sort']) ? array_map(fn ($item) => SearchCustomersRequestApplicationJsonPropertySortItem::fromArray($item), $data['sort']) : null,
            search: isset($data['search']) ? SearchCustomersRequestApplicationJsonPropertySearch::fromArray($data['search']) : null,
            includes: isset($data['includes']) ? array_map(fn ($item) => SearchCustomersRequestApplicationJsonPropertyIncludesItem::fromArray($item), $data['includes']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['filters', 'sort', 'search', 'includes']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'filters' => $this->filters !== null ? array_map(fn ($item) => $item->toArray(), $this->filters) : null,
            'sort' => $this->sort !== null ? array_map(fn ($item) => $item->toArray(), $this->sort) : null,
            'search' => $this->search?->toArray(),
            'includes' => $this->includes !== null ? array_map(fn ($item) => $item->toArray(), $this->includes) : null,
        ], [], $this->presentFields));
    }
}
