<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkSearchInvoicesRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkSearchInvoicesRequestApplicationJson', 'required' => [], 'properties' => ['search' => ['kind' => 'primitive', 'type' => 'string'], 'search_by' => ['kind' => 'enum', 'values' => ['default', 'transaction_id', 'serial_code', 'additional_info', 'product_name', 'discord_data', 'crypto_txid', 'crypto_address', 'coupon_code']], 'id' => ['kind' => 'primitive', 'type' => 'string'], 'email' => ['kind' => 'primitive', 'type' => 'string'], 'transaction_id' => ['kind' => 'primitive', 'type' => 'string'], 'serial_code' => ['kind' => 'primitive', 'type' => 'string'], 'additional_info' => ['kind' => 'primitive', 'type' => 'string'], 'product_name' => ['kind' => 'primitive', 'type' => 'string'], 'discord_data' => ['kind' => 'primitive', 'type' => 'string'], 'crypto_txid' => ['kind' => 'primitive', 'type' => 'string'], 'crypto_address' => ['kind' => 'primitive', 'type' => 'string'], 'coupon_code' => ['kind' => 'primitive', 'type' => 'string'], 'status' => ['kind' => 'array', 'items' => ['kind' => 'enum', 'values' => ['PENDING', 'REVERSED', 'PARTIAL', 'VOIDED', 'REFUNDED', 'PAID', 'COMPLETED', 'DISPUTING', 'REVIEW', 'FAILED']]], 'payment_methods' => ['kind' => 'array', 'items' => ['kind' => 'enum', 'values' => ['AUTHNET', 'BTCPAY', 'CASHAPP', 'COINBASE', 'PADDLE', 'PAYDASH', 'PAYPAL', 'PAYSTACK', 'SQUARE', 'STRIPE', 'VENMO', 'NMI', 'MERCADO_PAGO', 'MOLLIE', 'RAZORPAY', 'CUSTOM_PAYMENT_METHOD', 'LIFI', 'BTC', 'LTC', 'ETH', 'XMR', 'SOL', 'ADA', 'BNB', 'TRX', 'MATIC', 'ETH_USDT', 'ETH_USDC', 'ETH_UNI', 'ETH_SHIB', 'ETH_DAI', 'BNB_USDT', 'BNB_USDC', 'TRX_USDT', 'TRX_USDC', 'SOL_USDT', 'SOL_USDC']]], 'sort' => ['kind' => 'enum', 'values' => ['created_at', '-created_at']]], 'additionalProperties' => true];

    public function __construct(
        public ?string $search = null,
        public InvoicesSearchBy|string|null $searchBy = null,
        public ?string $id = null,
        public ?string $email = null,
        public ?string $transactionId = null,
        public ?string $serialCode = null,
        public ?string $additionalInfo = null,
        public ?string $productName = null,
        public ?string $discordData = null,
        public ?string $cryptoTxid = null,
        public ?string $cryptoAddress = null,
        public ?string $couponCode = null,
        /** @var array<\SellApp\Resource\Status>|null */
        public ?array $status = null,
        /** @var array<\SellApp\Resource\PaymentMethod>|null */
        public ?array $paymentMethods = null,
        public InvoicesSort|string|null $sort = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            search: $data['search'] ?? null,
            searchBy: isset($data['search_by']) ? InvoicesSearchBy::tryFrom($data['search_by']) ?? $data['search_by'] : null,
            id: $data['id'] ?? null,
            email: $data['email'] ?? null,
            transactionId: $data['transaction_id'] ?? null,
            serialCode: $data['serial_code'] ?? null,
            additionalInfo: $data['additional_info'] ?? null,
            productName: $data['product_name'] ?? null,
            discordData: $data['discord_data'] ?? null,
            cryptoTxid: $data['crypto_txid'] ?? null,
            cryptoAddress: $data['crypto_address'] ?? null,
            couponCode: $data['coupon_code'] ?? null,
            status: isset($data['status']) ? array_map(fn ($item) => Status::tryFrom($item) ?? $item, $data['status']) : null,
            paymentMethods: isset($data['payment_methods']) ? array_map(fn ($item) => PaymentMethod::tryFrom($item) ?? $item, $data['payment_methods']) : null,
            sort: isset($data['sort']) ? InvoicesSort::tryFrom($data['sort']) ?? $data['sort'] : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['search', 'search_by', 'id', 'email', 'transaction_id', 'serial_code', 'additional_info', 'product_name', 'discord_data', 'crypto_txid', 'crypto_address', 'coupon_code', 'status', 'payment_methods', 'sort']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'search' => $this->search,
            'search_by' => $this->searchBy instanceof \BackedEnum ? $this->searchBy->value : $this->searchBy,
            'id' => $this->id,
            'email' => $this->email,
            'transaction_id' => $this->transactionId,
            'serial_code' => $this->serialCode,
            'additional_info' => $this->additionalInfo,
            'product_name' => $this->productName,
            'discord_data' => $this->discordData,
            'crypto_txid' => $this->cryptoTxid,
            'crypto_address' => $this->cryptoAddress,
            'coupon_code' => $this->couponCode,
            'status' => $this->status !== null ? array_map(fn ($item) => $item instanceof \BackedEnum ? $item->value : $item, $this->status) : null,
            'payment_methods' => $this->paymentMethods !== null ? array_map(fn ($item) => $item instanceof \BackedEnum ? $item->value : $item, $this->paymentMethods) : null,
            'sort' => $this->sort instanceof \BackedEnum ? $this->sort->value : $this->sort,
        ], [], $this->presentFields));
    }
}
