<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkSearchOrderSLineItemsRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkSearchOrderSLineItemsRequestApplicationJson', 'required' => [], 'properties' => ['filters' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem'], 'maxItems' => 25], 'sort' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchOrderSLineItemsRequestApplicationJsonPropertySortItem'], 'maxItems' => 4], 'pagination' => ['kind' => 'model', 'class' => 'SearchOrderSLineItemsRequestApplicationJsonPropertyPagination']], 'additionalProperties' => false];

    public function __construct(
        /** @var array<\SellApp\Resource\SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem>|null */
        public ?array $filters = null,
        /** @var array<\SellApp\Resource\SearchOrderSLineItemsRequestApplicationJsonPropertySortItem>|null */
        public ?array $sort = null,
        public ?SearchOrderSLineItemsRequestApplicationJsonPropertyPagination $pagination = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            filters: isset($data['filters']) ? array_map(fn ($item) => SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem::fromArray($item), $data['filters']) : null,
            sort: isset($data['sort']) ? array_map(fn ($item) => SearchOrderSLineItemsRequestApplicationJsonPropertySortItem::fromArray($item), $data['sort']) : null,
            pagination: isset($data['pagination']) ? SearchOrderSLineItemsRequestApplicationJsonPropertyPagination::fromArray($data['pagination']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['filters', 'sort', 'pagination']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'filters' => $this->filters !== null ? array_map(fn ($item) => $item->toArray(), $this->filters) : null,
            'sort' => $this->sort !== null ? array_map(fn ($item) => $item->toArray(), $this->sort) : null,
            'pagination' => $this->pagination?->toArray(),
        ], [], $this->presentFields));
    }
}
