<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkSearchTicketMessagesResponseValue200ApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkSearchTicketMessagesResponseValue200ApplicationJson', 'required' => ['data', 'links', 'meta'], 'properties' => ['data' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem']], 'links' => ['kind' => 'model', 'class' => 'SearchTicketMessagesResponseValue200ApplicationJsonPropertyLinks'], 'meta' => ['kind' => 'model', 'class' => 'SearchTicketMessagesResponseValue200ApplicationJsonPropertyMeta']], 'additionalProperties' => true];

    public function __construct(
        /** @var array<\SellApp\Resource\SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem> */
        public array $data,
        public SearchTicketMessagesResponseValue200ApplicationJsonPropertyLinks $links,
        public SearchTicketMessagesResponseValue200ApplicationJsonPropertyMeta $meta,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            data: array_map(fn ($item) => SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem::fromArray($item), $data['data']),
            links: SearchTicketMessagesResponseValue200ApplicationJsonPropertyLinks::fromArray($data['links']),
            meta: SearchTicketMessagesResponseValue200ApplicationJsonPropertyMeta::fromArray($data['meta']),
            additionalProperties: SchemaValidator::unknownFields($data, ['data', 'links', 'meta']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'data' => array_map(fn ($item) => $item->toArray(), $this->data),
            'links' => $this->links->toArray(),
            'meta' => $this->meta->toArray(),
        ], ['data', 'links', 'meta'], $this->presentFields));
    }
}
