<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkUpdateRewardCouponTemplateRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkUpdateRewardCouponTemplateRequestApplicationJson', 'required' => [], 'properties' => ['name' => ['kind' => 'primitive', 'type' => 'string', 'minLength' => 1, 'maxLength' => 120], 'type' => ['kind' => 'enum', 'values' => ['PERCENTAGE', 'AMOUNT']], 'discount' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'string', 'minimum' => 0.01], ['kind' => 'primitive', 'type' => 'number', 'minimum' => 0.01]]], 'store_wide' => ['kind' => 'primitive', 'type' => 'boolean'], 'minimum_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'string', 'minimum' => 0.01], ['kind' => 'primitive', 'type' => 'number', 'minimum' => 0.01]]]], 'maximum_discount_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'string', 'minimum' => 0.01], ['kind' => 'primitive', 'type' => 'number', 'minimum' => 0.01]]]], 'expires_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'expires_after_days' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1, 'maximum' => 4294967295]], 'redemption_mode' => ['kind' => 'enum', 'values' => ['customer_locked', 'shareable_once']], 'is_active' => ['kind' => 'primitive', 'type' => 'boolean'], 'listing_ids' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer']], 'expected_updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public ?string $name = null,
        public SdkCreateCouponRequestApplicationJsonType|string|null $type = null,
        public string|float|null $discount = null,
        public ?bool $storeWide = null,
        public string|float|null $minimumAmount = null,
        public string|float|null $maximumDiscountAmount = null,
        public ?\DateTimeImmutable $expiresAt = null,
        public ?int $expiresAfterDays = null,
        public SdkCreateRewardCouponTemplateRequestApplicationJsonRedemptionMode|string|null $redemptionMode = null,
        public ?bool $isActive = null,
        /** @var array<int>|null */
        public ?array $listingIds = null,
        public ?\DateTimeImmutable $expectedUpdatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            name: $data['name'] ?? null,
            type: isset($data['type']) ? SdkCreateCouponRequestApplicationJsonType::tryFrom($data['type']) ?? $data['type'] : null,
            discount: $data['discount'] ?? null,
            storeWide: $data['store_wide'] ?? null,
            minimumAmount: $data['minimum_amount'] ?? null,
            maximumDiscountAmount: $data['maximum_discount_amount'] ?? null,
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
            expiresAfterDays: $data['expires_after_days'] ?? null,
            redemptionMode: isset($data['redemption_mode']) ? SdkCreateRewardCouponTemplateRequestApplicationJsonRedemptionMode::tryFrom($data['redemption_mode']) ?? $data['redemption_mode'] : null,
            isActive: $data['is_active'] ?? null,
            listingIds: $data['listing_ids'] ?? null,
            expectedUpdatedAt: isset($data['expected_updated_at']) ? new \DateTimeImmutable($data['expected_updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['name', 'type', 'discount', 'store_wide', 'minimum_amount', 'maximum_discount_amount', 'expires_at', 'expires_after_days', 'redemption_mode', 'is_active', 'listing_ids', 'expected_updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'name' => $this->name,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'discount' => $this->discount,
            'store_wide' => $this->storeWide,
            'minimum_amount' => $this->minimumAmount,
            'maximum_discount_amount' => $this->maximumDiscountAmount,
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'expires_after_days' => $this->expiresAfterDays,
            'redemption_mode' => $this->redemptionMode instanceof \BackedEnum ? $this->redemptionMode->value : $this->redemptionMode,
            'is_active' => $this->isActive,
            'listing_ids' => $this->listingIds,
            'expected_updated_at' => $this->expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], [], $this->presentFields));
    }
}
