<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkUpdateTicketRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkUpdateTicketRequestApplicationJson', 'required' => [], 'properties' => ['status' => ['kind' => 'enum', 'values' => ['OPEN', 'CLOSED']], 'archived' => ['kind' => 'primitive', 'type' => 'boolean']], 'additionalProperties' => true];

    public function __construct(
        public SdkUpdateTicketRequestApplicationJsonStatus|string|null $status = null,
        public ?bool $archived = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            status: isset($data['status']) ? SdkUpdateTicketRequestApplicationJsonStatus::tryFrom($data['status']) ?? $data['status'] : null,
            archived: $data['archived'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['status', 'archived']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'status' => $this->status instanceof \BackedEnum ? $this->status->value : $this->status,
            'archived' => $this->archived,
        ], [], $this->presentFields));
    }
}
