<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkUpdatePromotionRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkUpdatePromotionRequestApplicationJson', 'required' => [], 'properties' => ['name' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255], 'status' => ['kind' => 'enum', 'values' => ['active', 'disabled']], 'starts_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'ends_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'priority' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0, 'maximum' => 2147483647], 'is_stackable' => ['kind' => 'primitive', 'type' => 'boolean'], 'max_redemptions' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1, 'maximum' => 4294967295]], 'phases' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'UpdatePromotionRequestApplicationJsonPropertyPhasesItem'], 'minItems' => 1]], 'additionalProperties' => true];

    public function __construct(
        public ?string $name = null,
        public SdkCreatePromotionRequestApplicationJsonStatus|string|null $status = null,
        public ?\DateTimeImmutable $startsAt = null,
        /** A date and time after starts_at and after the current time, or null for no end date. */
        public ?\DateTimeImmutable $endsAt = null,
        public ?int $priority = null,
        public ?bool $isStackable = null,
        public ?int $maxRedemptions = null,
        /**
         * The complete ordered phase set. Array order becomes phase position.
         * @var array<\SellApp\Resource\UpdatePromotionRequestApplicationJsonPropertyPhasesItem>|null
         */
        public ?array $phases = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            name: $data['name'] ?? null,
            status: isset($data['status']) ? SdkCreatePromotionRequestApplicationJsonStatus::tryFrom($data['status']) ?? $data['status'] : null,
            startsAt: isset($data['starts_at']) ? new \DateTimeImmutable($data['starts_at']) : null,
            endsAt: isset($data['ends_at']) ? new \DateTimeImmutable($data['ends_at']) : null,
            priority: $data['priority'] ?? null,
            isStackable: $data['is_stackable'] ?? null,
            maxRedemptions: $data['max_redemptions'] ?? null,
            phases: isset($data['phases']) ? array_map(fn ($item) => UpdatePromotionRequestApplicationJsonPropertyPhasesItem::fromArray($item), $data['phases']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['name', 'status', 'starts_at', 'ends_at', 'priority', 'is_stackable', 'max_redemptions', 'phases']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'name' => $this->name,
            'status' => $this->status instanceof \BackedEnum ? $this->status->value : $this->status,
            'starts_at' => $this->startsAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'ends_at' => $this->endsAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'priority' => $this->priority,
            'is_stackable' => $this->isStackable,
            'max_redemptions' => $this->maxRedemptions,
            'phases' => $this->phases !== null ? array_map(fn ($item) => $item->toArray(), $this->phases) : null,
        ], [], $this->presentFields));
    }
}
