<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkUpdateLicenseKeyRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkUpdateLicenseKeyRequestApplicationJson', 'required' => [], 'properties' => ['limit' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer']], 'expires_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'active' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'boolean']]], 'additionalProperties' => true];

    public function __construct(
        public ?int $limit = null,
        public ?\DateTimeImmutable $expiresAt = null,
        public ?bool $active = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            limit: $data['limit'] ?? null,
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
            active: $data['active'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['limit', 'expires_at', 'active']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'limit' => $this->limit,
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'active' => $this->active,
        ], [], $this->presentFields));
    }
}
