<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum SdkUpdateBookingConfigurationRequestApplicationJsonVideoProvider: string
{
    case None = 'none';
    case GoogleMeet = 'google_meet';
    case Zoom = 'zoom';
}
