<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkV2SearchCouponsRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkV2SearchCouponsRequestApplicationJson', 'required' => [], 'properties' => ['filters' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'V2SearchCouponsRequestApplicationJsonPropertyFiltersItem']], 'sort' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'V2SearchCouponsRequestApplicationJsonPropertySortItem']], 'search' => ['kind' => 'model', 'class' => 'V2SearchCouponsRequestApplicationJsonPropertySearch'], 'includes' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'V2SearchCouponsRequestApplicationJsonPropertyIncludesItem']]], 'additionalProperties' => true];

    public function __construct(
        /** @var array<\SellApp\Resource\V2SearchCouponsRequestApplicationJsonPropertyFiltersItem>|null */
        public ?array $filters = null,
        /** @var array<\SellApp\Resource\V2SearchCouponsRequestApplicationJsonPropertySortItem>|null */
        public ?array $sort = null,
        public ?V2SearchCouponsRequestApplicationJsonPropertySearch $search = null,
        /** @var array<\SellApp\Resource\V2SearchCouponsRequestApplicationJsonPropertyIncludesItem>|null */
        public ?array $includes = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            filters: isset($data['filters']) ? array_map(fn ($item) => V2SearchCouponsRequestApplicationJsonPropertyFiltersItem::fromArray($item), $data['filters']) : null,
            sort: isset($data['sort']) ? array_map(fn ($item) => V2SearchCouponsRequestApplicationJsonPropertySortItem::fromArray($item), $data['sort']) : null,
            search: isset($data['search']) ? V2SearchCouponsRequestApplicationJsonPropertySearch::fromArray($data['search']) : null,
            includes: isset($data['includes']) ? array_map(fn ($item) => V2SearchCouponsRequestApplicationJsonPropertyIncludesItem::fromArray($item), $data['includes']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['filters', 'sort', 'search', 'includes']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'filters' => $this->filters !== null ? array_map(fn ($item) => $item->toArray(), $this->filters) : null,
            'sort' => $this->sort !== null ? array_map(fn ($item) => $item->toArray(), $this->sort) : null,
            'search' => $this->search?->toArray(),
            'includes' => $this->includes !== null ? array_map(fn ($item) => $item->toArray(), $this->includes) : null,
        ], [], $this->presentFields));
    }
}
