<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SdkV2ReplaceCouponRequestApplicationJson implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SdkV2ReplaceCouponRequestApplicationJson', 'required' => [], 'properties' => ['code' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255], 'type' => ['kind' => 'enum', 'values' => ['PERCENTAGE', 'AMOUNT']], 'discount' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'number', 'minimum' => 1, 'maxLength' => 255], ['kind' => 'primitive', 'type' => 'string', 'minimum' => 1, 'maxLength' => 255]]], 'store_wide' => ['kind' => 'primitive', 'type' => 'boolean'], 'products' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer'], 'minItems' => 1], 'product_variants' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'integer']], 'limit' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 1]], 'expires_at' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'minimum_amount' => ['kind' => 'nullable', 'inner' => ['kind' => 'union', 'variants' => [['kind' => 'primitive', 'type' => 'number', 'minimum' => 1, 'maxLength' => 255], ['kind' => 'primitive', 'type' => 'string', 'minimum' => 1, 'maxLength' => 255]]]]], 'additionalProperties' => true];

    public function __construct(
        public ?string $code = null,
        public SdkCreateCouponRequestApplicationJsonType|string|null $type = null,
        /** A decimal discount value of at least 1. Percentage discounts cannot exceed 100; amount discounts use the store currency's major unit. */
        public float|string|null $discount = null,
        public ?bool $storeWide = null,
        /**
         * Product IDs the coupon applies to when store_wide is false.
         * @var array<int>|null
         */
        public ?array $products = null,
        /**
         * Optional variant restrictions. Omit to preserve existing restrictions or send an empty array to allow every variant of the selected products.
         * @var array<int>|null
         */
        public ?array $productVariants = null,
        public ?int $limit = null,
        /** A future date and time, or null for no expiry. */
        public ?\DateTimeImmutable $expiresAt = null,
        /** A decimal minimum order amount in the store currency's major unit, or null for no minimum. */
        public float|string|null $minimumAmount = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            code: $data['code'] ?? null,
            type: isset($data['type']) ? SdkCreateCouponRequestApplicationJsonType::tryFrom($data['type']) ?? $data['type'] : null,
            discount: $data['discount'] ?? null,
            storeWide: $data['store_wide'] ?? null,
            products: $data['products'] ?? null,
            productVariants: $data['product_variants'] ?? null,
            limit: $data['limit'] ?? null,
            expiresAt: isset($data['expires_at']) ? new \DateTimeImmutable($data['expires_at']) : null,
            minimumAmount: $data['minimum_amount'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['code', 'type', 'discount', 'store_wide', 'products', 'product_variants', 'limit', 'expires_at', 'minimum_amount']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'code' => $this->code,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'discount' => $this->discount,
            'store_wide' => $this->storeWide,
            'products' => $this->products,
            'product_variants' => $this->productVariants,
            'limit' => $this->limit,
            'expires_at' => $this->expiresAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'minimum_amount' => $this->minimumAmount,
        ], [], $this->presentFields));
    }
}
