<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum SearchCreditsProductsRequestApplicationJsonPropertyFiltersItemField: string
{
    case Id = 'id';
    case Visibility = 'visibility';
    case IsDraft = 'is_draft';
}
