<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SearchProductVariantsRequestApplicationJsonPropertyFiltersItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SearchProductVariantsRequestApplicationJsonPropertyFiltersItem', 'required' => [], 'properties' => ['field' => ['kind' => 'primitive', 'type' => 'string'], 'operator' => ['kind' => 'primitive', 'type' => 'string'], 'value' => ['kind' => 'primitive', 'type' => 'unknown'], 'type' => ['kind' => 'enum', 'values' => ['and', 'or']], 'nested' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchProductVariantsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem']]], 'additionalProperties' => true];

    public function __construct(
        public ?string $field = null,
        public ?string $operator = null,
        public mixed $value = null,
        public SearchGroupsRequestApplicationJsonPropertyFiltersItemType|string|null $type = null,
        /** @var array<\SellApp\Resource\SearchProductVariantsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem>|null */
        public ?array $nested = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            field: $data['field'] ?? null,
            operator: $data['operator'] ?? null,
            value: $data['value'] ?? null,
            type: isset($data['type']) ? SearchGroupsRequestApplicationJsonPropertyFiltersItemType::tryFrom($data['type']) ?? $data['type'] : null,
            nested: isset($data['nested']) ? array_map(fn ($item) => SearchProductVariantsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem::fromArray($item), $data['nested']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['field', 'operator', 'value', 'type', 'nested']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'field' => $this->field,
            'operator' => $this->operator,
            'value' => $this->value,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'nested' => $this->nested !== null ? array_map(fn ($item) => $item->toArray(), $this->nested) : null,
        ], [], $this->presentFields));
    }
}
