<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing', 'required' => ['humble', 'frequency', 'type', 'price'], 'properties' => ['humble' => ['kind' => 'primitive', 'type' => 'boolean'], 'frequency' => ['kind' => 'model', 'class' => 'SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency'], 'type' => ['kind' => 'primitive', 'type' => 'string'], 'price' => ['kind' => 'model', 'class' => 'SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice']], 'additionalProperties' => true];

    public function __construct(
        public bool $humble,
        public SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency $frequency,
        public string $type,
        public SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice $price,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            humble: $data['humble'],
            frequency: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency::fromArray($data['frequency']),
            type: $data['type'],
            price: SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice::fromArray($data['price']),
            additionalProperties: SchemaValidator::unknownFields($data, ['humble', 'frequency', 'type', 'price']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'humble' => $this->humble,
            'frequency' => $this->frequency->toArray(),
            'type' => $this->type,
            'price' => $this->price->toArray(),
        ], ['humble', 'frequency', 'type', 'price'], $this->presentFields));
    }
}
