<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

enum SearchCustomersRequestApplicationJsonPropertyFiltersItemOperator: string
{
    case  = '=';
    case 2 = '!=';
    case 3 = '<>';
    case 4 = '<';
    case 5 = '<=';
    case 6 = '>';
    case 7 = '>=';
    case Like = 'like';
    case NotLike = 'not like';
}
