<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SearchWebhookChannelsRequestApplicationJsonPropertySearch implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SearchWebhookChannelsRequestApplicationJsonPropertySearch', 'required' => [], 'properties' => ['value' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 255]]], 'additionalProperties' => true];

    public function __construct(
        public ?string $value = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            value: $data['value'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['value']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'value' => $this->value,
        ], [], $this->presentFields));
    }
}
