<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts', 'required' => ['coupon', 'modifiers'], 'properties' => ['coupon' => ['kind' => 'nullable', 'inner' => ['kind' => 'model', 'class' => 'SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon']], 'modifiers' => ['kind' => 'array', 'items' => ['kind' => 'model', 'class' => 'SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem']]], 'additionalProperties' => true];

    public function __construct(
        public ?SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon $coupon,
        /**
         * Safe historical summaries of discount, fee, and pricing modifiers. Only the documented fields are returned. Coupon codes are included only when the coupon is verified as belonging to the authenticated store.
         * @var array<\SellApp\Resource\SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem>
         */
        public array $modifiers,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            coupon: isset($data['coupon']) ? SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyCoupon::fromArray($data['coupon']) : null,
            modifiers: array_map(fn ($item) => SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscountsPropertyModifiersItem::fromArray($item), $data['modifiers']),
            additionalProperties: SchemaValidator::unknownFields($data, ['coupon', 'modifiers']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'coupon' => $this->coupon?->toArray(),
            'modifiers' => array_map(fn ($item) => $item->toArray(), $this->modifiers),
        ], ['coupon', 'modifiers'], $this->presentFields));
    }
}
