<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral', 'required' => ['id', 'status', 'amount_usd_cents'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'status' => ['kind' => 'primitive', 'type' => 'string'], 'amount_usd_cents' => ['kind' => 'primitive', 'type' => 'integer']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public string $status,
        /** Attributed affiliate amount in US dollar cents. */
        public int $amountUsdCents,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            status: $data['status'],
            amountUsdCents: $data['amount_usd_cents'],
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'status', 'amount_usd_cents']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'status' => $this->status,
            'amount_usd_cents' => $this->amountUsdCents,
        ], ['id', 'status', 'amount_usd_cents'], $this->presentFields));
    }
}
