<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class UpdateCourseLessonRequestApplicationJsonPropertyAssignmentPropertyQuestionsItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'UpdateCourseLessonRequestApplicationJsonPropertyAssignmentPropertyQuestionsItem', 'required' => ['prompt'], 'properties' => ['prompt' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 65535], 'solution' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string', 'maxLength' => 65535]]], 'additionalProperties' => true];

    public function __construct(
        public string $prompt,
        public ?string $solution = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            prompt: $data['prompt'],
            solution: $data['solution'] ?? null,
            additionalProperties: SchemaValidator::unknownFields($data, ['prompt', 'solution']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'prompt' => $this->prompt,
            'solution' => $this->solution,
        ], ['prompt'], $this->presentFields));
    }
}
