<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class UpdateAffiliatePayoutStatusResponseValue200ApplicationJsonPropertyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'UpdateAffiliatePayoutStatusResponseValue200ApplicationJsonPropertyData', 'required' => ['id', 'affiliate_id', 'amount_usd_cents', 'status', 'payout_account', 'referrals_count'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'affiliate_id' => ['kind' => 'primitive', 'type' => 'integer'], 'amount_usd_cents' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0], 'status' => ['kind' => 'enum', 'values' => ['due', 'paid', 'cancelled']], 'payout_account' => ['kind' => 'primitive', 'type' => 'string'], 'referrals_count' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0], 'affiliate_email' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'email'], 'payout_method' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'string']], 'created_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time'], 'updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public int $affiliateId,
        public int $amountUsdCents,
        public GetAffiliatePayoutResponseValue200ApplicationJsonPropertyDataStatus|string $status,
        /** A masked payout destination. Full payout credentials are never returned. */
        public string $payoutAccount,
        public int $referralsCount,
        public ?string $affiliateEmail = null,
        public ?string $payoutMethod = null,
        public ?\DateTimeImmutable $createdAt = null,
        public ?\DateTimeImmutable $updatedAt = null,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            affiliateId: $data['affiliate_id'],
            amountUsdCents: $data['amount_usd_cents'],
            status: GetAffiliatePayoutResponseValue200ApplicationJsonPropertyDataStatus::tryFrom($data['status']) ?? $data['status'],
            payoutAccount: $data['payout_account'],
            referralsCount: $data['referrals_count'],
            affiliateEmail: $data['affiliate_email'] ?? null,
            payoutMethod: $data['payout_method'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            updatedAt: isset($data['updated_at']) ? new \DateTimeImmutable($data['updated_at']) : null,
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'affiliate_id', 'amount_usd_cents', 'status', 'payout_account', 'referrals_count', 'affiliate_email', 'payout_method', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'affiliate_id' => $this->affiliateId,
            'amount_usd_cents' => $this->amountUsdCents,
            'status' => $this->status instanceof \BackedEnum ? $this->status->value : $this->status,
            'payout_account' => $this->payoutAccount,
            'referrals_count' => $this->referralsCount,
            'affiliate_email' => $this->affiliateEmail,
            'payout_method' => $this->payoutMethod,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'affiliate_id', 'amount_usd_cents', 'status', 'payout_account', 'referrals_count'], $this->presentFields));
    }
}
