<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class UpdateAffiliateStatusResponseValue200ApplicationJsonPropertyDataPropertyBalances implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'UpdateAffiliateStatusResponseValue200ApplicationJsonPropertyDataPropertyBalances', 'required' => ['available_usd_cents', 'pending_usd_cents', 'paid_usd_cents'], 'properties' => ['available_usd_cents' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0], 'pending_usd_cents' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0], 'paid_usd_cents' => ['kind' => 'primitive', 'type' => 'integer', 'minimum' => 0]], 'additionalProperties' => true];

    public function __construct(
        public int $availableUsdCents,
        public int $pendingUsdCents,
        public int $paidUsdCents,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            availableUsdCents: $data['available_usd_cents'],
            pendingUsdCents: $data['pending_usd_cents'],
            paidUsdCents: $data['paid_usd_cents'],
            additionalProperties: SchemaValidator::unknownFields($data, ['available_usd_cents', 'pending_usd_cents', 'paid_usd_cents']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'available_usd_cents' => $this->availableUsdCents,
            'pending_usd_cents' => $this->pendingUsdCents,
            'paid_usd_cents' => $this->paidUsdCents,
        ], ['available_usd_cents', 'pending_usd_cents', 'paid_usd_cents'], $this->presentFields));
    }
}
