<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyDeliverable implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyDeliverable', 'required' => ['data', 'types'], 'properties' => ['data' => ['kind' => 'model', 'class' => 'UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData'], 'types' => ['kind' => 'array', 'items' => ['kind' => 'primitive', 'type' => 'string']]], 'additionalProperties' => true];

    public function __construct(
        public UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData $data,
        /** @var array<string> */
        public array $types,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            data: UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData::fromArray($data['data']),
            types: $data['types'],
            additionalProperties: SchemaValidator::unknownFields($data, ['data', 'types']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'data' => $this->data->toArray(),
            'types' => $this->types,
        ], ['data', 'types'], $this->presentFields));
    }
}
