<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class UpdateHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'UpdateHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem', 'required' => ['id', 'sort_order', 'type', 'url', 'filename', 'size', 'mime_type', 'cta_title', 'product_id', 'created_at', 'updated_at'], 'properties' => ['id' => ['kind' => 'primitive', 'type' => 'integer'], 'sort_order' => ['kind' => 'primitive', 'type' => 'integer'], 'type' => ['kind' => 'enum', 'values' => ['image', 'video']], 'url' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'uri'], 'filename' => ['kind' => 'primitive', 'type' => 'string'], 'size' => ['kind' => 'primitive', 'type' => 'integer'], 'mime_type' => ['kind' => 'primitive', 'type' => 'string'], 'cta_title' => ['kind' => 'primitive', 'type' => 'string'], 'product_id' => ['kind' => 'nullable', 'inner' => ['kind' => 'primitive', 'type' => 'integer']], 'created_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time'], 'updated_at' => ['kind' => 'primitive', 'type' => 'string', 'format' => 'date-time']], 'additionalProperties' => true];

    public function __construct(
        public int $id,
        public int $sortOrder,
        public AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType|string $type,
        public string $url,
        public string $filename,
        public int $size,
        public string $mimeType,
        public string $ctaTitle,
        public ?int $productId,
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $updatedAt,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            id: $data['id'],
            sortOrder: $data['sort_order'],
            type: AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType::tryFrom($data['type']) ?? $data['type'],
            url: $data['url'],
            filename: $data['filename'],
            size: $data['size'],
            mimeType: $data['mime_type'],
            ctaTitle: $data['cta_title'],
            productId: $data['product_id'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            additionalProperties: SchemaValidator::unknownFields($data, ['id', 'sort_order', 'type', 'url', 'filename', 'size', 'mime_type', 'cta_title', 'product_id', 'created_at', 'updated_at']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'id' => $this->id,
            'sort_order' => $this->sortOrder,
            'type' => $this->type instanceof \BackedEnum ? $this->type->value : $this->type,
            'url' => $this->url,
            'filename' => $this->filename,
            'size' => $this->size,
            'mime_type' => $this->mimeType,
            'cta_title' => $this->ctaTitle,
            'product_id' => $this->productId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], ['id', 'sort_order', 'type', 'url', 'filename', 'size', 'mime_type', 'cta_title', 'product_id', 'created_at', 'updated_at'], $this->presentFields));
    }
}
