<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Resource;

readonly class ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2 implements \JsonSerializable
{
    use JsonSerializableTrait;

    private const SCHEMA = ['name' => 'ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2', 'required' => ['public_key', 'access_token', 'webhook_secret'], 'properties' => ['public_key' => ['kind' => 'primitive', 'type' => 'string'], 'access_token' => ['kind' => 'primitive', 'type' => 'string'], 'webhook_secret' => ['kind' => 'primitive', 'type' => 'string']], 'additionalProperties' => true];

    public function __construct(
        /** Write-only secret. SellApp never returns the stored value. */
        public string $publicKey,
        /** Write-only secret. SellApp never returns the stored value. */
        public string $accessToken,
        /** Write-only secret. SellApp never returns the stored value. */
        public string $webhookSecret,
        /** @var array<string, mixed> */
        public array $additionalProperties = [],
        private array $presentFields = [],
    ) {
    }

    public static function fromArray(array $data): self
    {
        self::validate($data, 'response');
        return new self(
            publicKey: $data['public_key'],
            accessToken: $data['access_token'],
            webhookSecret: $data['webhook_secret'],
            additionalProperties: SchemaValidator::unknownFields($data, ['public_key', 'access_token', 'webhook_secret']),
            presentFields: array_keys($data),
        );
    }

    public static function validate(array $data, string $direction = 'request'): void
    {
        SchemaValidator::validateModel($data, self::SCHEMA, $direction);
    }

    public function toArray(): array
    {
        return array_replace($this->additionalProperties, SchemaValidator::presentFields([
            'public_key' => $this->publicKey,
            'access_token' => $this->accessToken,
            'webhook_secret' => $this->webhookSecret,
        ], ['public_key', 'access_token', 'webhook_secret'], $this->presentFields));
    }
}
