<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class AccountTest extends TestCase
{
    use TestHelper;

    public function testGetAccount(): void
    {
        $fixture = $this->loadFixture('sdk_get_account_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->getAccount();
        $this->assertInstanceOf(\SellApp\Resource\SdkGetAccountResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/me', $request->getUri()->getPath());
    }

    public function testListStores(): void
    {
        $fixture = $this->loadFixture('sdk_list_stores_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->listStores();
        $this->assertInstanceOf(\SellApp\Resource\SdkListStoresResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/stores', $request->getUri()->getPath());
    }

    public function testCreateStore(): void
    {
        $fixture = $this->loadFixture('sdk_create_store_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->createStore(name: 'enx', slug: 'enx');
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateStoreResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/stores', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('enx', $body['name']);
        $this->assertSame('enx', $body['slug']);
    }

    public function testGetStore(): void
    {
        $fixture = $this->loadFixture('sdk_get_store_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->getStore(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetStoreResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/stores/1', $request->getUri()->getPath());
    }

    public function testGetStorePermissions(): void
    {
        $fixture = $this->loadFixture('sdk_get_store_permissions_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->getStorePermissions();
        $this->assertInstanceOf(\SellApp\Resource\SdkGetStorePermissionsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/permissions', $request->getUri()->getPath());
    }
}
