<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class AffiliatesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_list_affiliates_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->affiliates()->list(status: \SellApp\Resource\AffiliatesStatus::Pending, search: 'test_value', limit: 1, page: 1);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/affiliates', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('pending', $query['status']);
        $this->assertSame('test_value', $query['search']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_affiliate_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->affiliates()->get(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetAffiliateResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/affiliates/1', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_affiliate_status_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->affiliates()->update(1, status: \SellApp\Resource\SdkUpdateAffiliateStatusRequestApplicationJsonStatus::Active);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateAffiliateStatusResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/affiliates/1/status', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_affiliates_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->affiliates()->list();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
