<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class CashbackRulesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('sdk_list_cashback_rules_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cashbackRules()->list();
        $this->assertInstanceOf(\SellApp\Resource\SdkListCashbackRulesResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules', $request->getUri()->getPath());
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sdk_create_cashback_rule_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cashbackRules()->create(percentBasis: 1, maximumCashbackCents: 1, isActive: true, productIds: []);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateCashbackRuleResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame(1, $body['percent_basis']);
        $this->assertTrue($body['is_active']);
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_cashback_rule_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cashbackRules()->replace(1, percentBasis: 1, maximumCashbackCents: 1, isActive: true, productIds: []);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceCashbackRuleResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules/1', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame(1, $body['percent_basis']);
        $this->assertTrue($body['is_active']);
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_cashback_rule_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cashbackRules()->update(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateCashbackRuleResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules/1', $request->getUri()->getPath());
    }

    public function testArchive(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->cashbackRules()->archive(1);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules/1', $request->getUri()->getPath());
    }

    public function testRestore(): void
    {
        $fixture = $this->loadFixture('sdk_restore_cashback_rule_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cashbackRules()->restore(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkRestoreCashbackRuleResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/cashback-rules/1/restore', $request->getUri()->getPath());
    }
}
