<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class CommunityConnectionsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('sdk_list_community_connections_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->communityConnections()->list();
        $this->assertInstanceOf(\SellApp\Resource\SdkListCommunityConnectionsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections', $request->getUri()->getPath());
    }

    public function testStart(): void
    {
        $fixture = $this->loadFixture('sdk_start_community_connection_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->communityConnections()->start(\SellApp\Resource\CommunityConnectionsPlatform::Discord);
        $this->assertInstanceOf(\SellApp\Resource\SdkStartCommunityConnectionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections/discord/connect', $request->getUri()->getPath());
    }

    public function testPoll(): void
    {
        $fixture = $this->loadFixture('sdk_poll_community_connection_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->communityConnections()->poll(\SellApp\Resource\CommunityConnectionsPlatform::Discord, statusToken: 'test_value');
        $this->assertInstanceOf(\SellApp\Resource\SdkPollCommunityConnectionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections/discord/status', $request->getUri()->getPath());
    }

    public function testComplete(): void
    {
        $fixture = $this->loadFixture('sdk_complete_community_connection_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->communityConnections()->complete(\SellApp\Resource\CommunityConnectionsPlatform::Discord, statusToken: 'test_value', serverId: 'test_value');
        $this->assertInstanceOf(\SellApp\Resource\SdkCompleteCommunityConnectionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections/discord/complete', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['status_token']);
        $this->assertSame('test_value', $body['server_id']);
    }

    public function testVerify(): void
    {
        $fixture = $this->loadFixture('sdk_verify_community_connection_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->communityConnections()->verify(\SellApp\Resource\CommunityConnectionsPlatform::Discord);
        $this->assertInstanceOf(\SellApp\Resource\SdkVerifyCommunityConnectionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections/discord/verify', $request->getUri()->getPath());
    }

    public function testDisconnect(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->communityConnections()->disconnect(\SellApp\Resource\CommunityConnectionsPlatform::Discord);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/community-connections/discord', $request->getUri()->getPath());
    }
}
