<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class CouponsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_list_coupons_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->list(limit: 1, page: 1, withTrashed: true, onlyTrashed: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
        $this->assertArrayHasKey('with_trashed', $query);
        $this->assertArrayHasKey('only_trashed', $query);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sdk_create_coupon_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->create(code: 'test_value', type: \SellApp\Resource\SdkCreateCouponRequestApplicationJsonType::Percentage, discount: 1, storeWide: true);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateCouponResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['code']);
        $this->assertTrue($body['store_wide']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->get(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/1', $request->getUri()->getPath());
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->replace(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/1', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->update(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/1', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->coupons()->delete(1);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/1', $request->getUri()->getPath());
    }

    public function testSearch(): void
    {
        $fixture = $this->loadFixture('list_search_coupons_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->search(filters: [], sort: [], search: \SellApp\Resource\SearchCouponsRequestApplicationJsonPropertySearch::fromArray($this->loadFixture('search_coupons_request_application_json_property_search')), includes: [], withTrashed: true, onlyTrashed: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/search', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('with_trashed', $query);
        $this->assertArrayHasKey('only_trashed', $query);
    }

    public function testBatchCreate(): void
    {
        $fixture = $this->loadFixture('sdk_batch_create_coupons_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->batchCreate(resources: []);
        $this->assertInstanceOf(\SellApp\Resource\SdkBatchCreateCouponsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/batch', $request->getUri()->getPath());
    }

    public function testBatchUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_batch_update_coupons_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->batchUpdate(resources: \SellApp\Resource\BatchUpdateCouponsRequestApplicationJsonPropertyResources::fromArray($this->loadFixture('batch_update_coupons_request_application_json_property_resources')));
        $this->assertInstanceOf(\SellApp\Resource\SdkBatchUpdateCouponsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/batch', $request->getUri()->getPath());
    }

    public function testBatchDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->coupons()->batchDelete(resources: []);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/coupons/batch', $request->getUri()->getPath());
    }

    public function testV2ListCoupons(): void
    {
        $fixture = $this->loadFixture('list_v_2_list_coupons_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2ListCoupons(limit: 1, page: 1, withTrashed: true, onlyTrashed: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
        $this->assertArrayHasKey('with_trashed', $query);
        $this->assertArrayHasKey('only_trashed', $query);
    }

    public function testV2CreateCoupon(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_create_coupon_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2CreateCoupon(code: 'test_value', type: \SellApp\Resource\SdkCreateCouponRequestApplicationJsonType::Percentage, discount: 1, storeWide: true);
        $this->assertInstanceOf(\SellApp\Resource\SdkV2CreateCouponResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['code']);
        $this->assertTrue($body['store_wide']);
    }

    public function testV2SearchCoupons(): void
    {
        $fixture = $this->loadFixture('list_v_2_search_coupons_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2SearchCoupons(filters: [], sort: [], search: \SellApp\Resource\V2SearchCouponsRequestApplicationJsonPropertySearch::fromArray($this->loadFixture('v_2_search_coupons_request_application_json_property_search')), includes: [], withTrashed: true, onlyTrashed: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/search', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('with_trashed', $query);
        $this->assertArrayHasKey('only_trashed', $query);
    }

    public function testV2GetCoupon(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_get_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2GetCoupon(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkV2GetCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/1', $request->getUri()->getPath());
    }

    public function testV2ReplaceCoupon(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_replace_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2ReplaceCoupon(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkV2ReplaceCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/1', $request->getUri()->getPath());
    }

    public function testV2UpdateCoupon(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_update_coupon_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2UpdateCoupon(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkV2UpdateCouponResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/1', $request->getUri()->getPath());
    }

    public function testV2DeleteCoupon(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->coupons()->v2DeleteCoupon(1);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/1', $request->getUri()->getPath());
    }

    public function testV2BatchCreateCoupons(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_batch_create_coupons_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2BatchCreateCoupons(resources: []);
        $this->assertInstanceOf(\SellApp\Resource\SdkV2BatchCreateCouponsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/batch', $request->getUri()->getPath());
    }

    public function testV2BatchUpdateCoupons(): void
    {
        $fixture = $this->loadFixture('sdk_v_2_batch_update_coupons_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->v2BatchUpdateCoupons(resources: \SellApp\Resource\V2BatchUpdateCouponsRequestApplicationJsonPropertyResources::fromArray($this->loadFixture('v_2_batch_update_coupons_request_application_json_property_resources')));
        $this->assertInstanceOf(\SellApp\Resource\SdkV2BatchUpdateCouponsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/batch', $request->getUri()->getPath());
    }

    public function testV2BatchDeleteCoupons(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->coupons()->v2BatchDeleteCoupons(resources: []);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/coupons/batch', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_coupons_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->coupons()->list();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
