<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class CustomerPortalTest extends TestCase
{
    use TestHelper;

    public function testGetCustomerPortalProfile(): void
    {
        $fixture = $this->loadFixture('sdk_get_customer_portal_profile_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->getCustomerPortalProfile();
        $this->assertInstanceOf(\SellApp\Resource\SdkGetCustomerPortalProfileResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/me', $request->getUri()->getPath());
    }

    public function testUpdateCustomerPortalProfile(): void
    {
        $fixture = $this->loadFixture('sdk_update_customer_portal_profile_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->updateCustomerPortalProfile();
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateCustomerPortalProfileResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/me', $request->getUri()->getPath());
    }

    public function testListCustomerPortalOrders(): void
    {
        $fixture = $this->loadFixture('list_customer_portal_order');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->listCustomerPortalOrders();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/orders', $request->getUri()->getPath());
    }

    public function testGetCustomerPortalOrder(): void
    {
        $fixture = $this->loadFixture('sdk_get_customer_portal_order_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->getCustomerPortalOrder(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetCustomerPortalOrderResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/orders/1', $request->getUri()->getPath());
    }

    public function testListCustomerPortalSubscriptions(): void
    {
        $fixture = $this->loadFixture('sdk_list_customer_portal_subscriptions_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->listCustomerPortalSubscriptions();
        $this->assertInstanceOf(\SellApp\Resource\SdkListCustomerPortalSubscriptionsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions', $request->getUri()->getPath());
    }

    public function testGetCustomerPortalSubscription(): void
    {
        $fixture = $this->loadFixture('sdk_get_customer_portal_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->getCustomerPortalSubscription(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetCustomerPortalSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1', $request->getUri()->getPath());
    }

    public function testGetCustomerPortalSubscriptionCapabilities(): void
    {
        $fixture = $this->loadFixture('sdk_get_customer_portal_subscription_capabilities_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->getCustomerPortalSubscriptionCapabilities(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/capabilities', $request->getUri()->getPath());
    }

    public function testListCustomerPortalEntitlements(): void
    {
        $fixture = $this->loadFixture('sdk_list_customer_portal_entitlements_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->listCustomerPortalEntitlements();
        $this->assertInstanceOf(\SellApp\Resource\SdkListCustomerPortalEntitlementsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/entitlements', $request->getUri()->getPath());
    }

    public function testCancelCustomerSubscriptionAtPeriodEnd(): void
    {
        $fixture = $this->loadFixture('sdk_cancel_customer_subscription_at_period_end_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->cancelCustomerSubscriptionAtPeriodEnd(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/cancel-period-end', $request->getUri()->getPath());
    }

    public function testCancelCustomerSubscriptionImmediately(): void
    {
        $fixture = $this->loadFixture('sdk_cancel_customer_subscription_immediately_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->cancelCustomerSubscriptionImmediately(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/cancel-immediately', $request->getUri()->getPath());
    }

    public function testPauseCustomerSubscription(): void
    {
        $fixture = $this->loadFixture('sdk_pause_customer_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->pauseCustomerSubscription(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkPauseCustomerSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/pause', $request->getUri()->getPath());
    }

    public function testResumeCustomerSubscription(): void
    {
        $fixture = $this->loadFixture('sdk_resume_customer_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->resumeCustomerSubscription(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkResumeCustomerSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/resume', $request->getUri()->getPath());
    }

    public function testUpdateCustomerSubscriptionPaymentMethod(): void
    {
        $fixture = $this->loadFixture('sdk_update_customer_subscription_payment_method_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->updateCustomerSubscriptionPaymentMethod(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/update-payment-method', $request->getUri()->getPath());
    }

    public function testPreviewCustomerSubscriptionPlanChange(): void
    {
        $fixture = $this->loadFixture('sdk_preview_customer_subscription_plan_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->previewCustomerSubscriptionPlanChange(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkPreviewCustomerSubscriptionPlanChangeResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/change-plan/preview', $request->getUri()->getPath());
    }

    public function testConfirmCustomerSubscriptionPlanChange(): void
    {
        $fixture = $this->loadFixture('sdk_confirm_customer_subscription_plan_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->confirmCustomerSubscriptionPlanChange(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/change-plan/confirm', $request->getUri()->getPath());
    }

    public function testPreviewCustomerSubscriptionRenewalDateChange(): void
    {
        $fixture = $this->loadFixture('sdk_preview_customer_subscription_renewal_date_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->previewCustomerSubscriptionRenewalDateChange(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/change-renewal-date/preview', $request->getUri()->getPath());
    }

    public function testConfirmCustomerSubscriptionRenewalDateChange(): void
    {
        $fixture = $this->loadFixture('sdk_confirm_customer_subscription_renewal_date_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->confirmCustomerSubscriptionRenewalDateChange(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkConfirmCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/customer-portal/subscriptions/1/actions/change-renewal-date/confirm', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_customer_portal_order');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->customerPortal()->listCustomerPortalOrders();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
