<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class InvoicesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_list_invoices_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->list(limit: 1, page: 1, search: 'test_value', searchBy: \SellApp\Resource\InvoicesSearchBy::Default, id: 'test_value', email: 'test_value', transactionId: 'test_value', serialCode: 'test_value', additionalInfo: 'test_value', productName: 'test_value', discordData: 'test_value', cryptoTxid: 'test_value', cryptoAddress: 'test_value', couponCode: 'test_value', status: [], paymentMethods: [], sort: \SellApp\Resource\InvoicesSort::CreatedAt);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
        $this->assertSame('test_value', $query['search']);
        $this->assertSame('default', $query['search_by']);
        $this->assertSame('test_value', $query['id']);
        $this->assertSame('test_value', $query['email']);
        $this->assertSame('test_value', $query['transaction_id']);
        $this->assertSame('test_value', $query['serial_code']);
        $this->assertSame('test_value', $query['additional_info']);
        $this->assertSame('test_value', $query['product_name']);
        $this->assertSame('test_value', $query['discord_data']);
        $this->assertSame('test_value', $query['crypto_txid']);
        $this->assertSame('test_value', $query['crypto_address']);
        $this->assertSame('test_value', $query['coupon_code']);
        $this->assertSame('created_at', $query['sort']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sdk_create_invoice_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->create(customerEmail: 'test_value', paymentMethod: \SellApp\Resource\PaymentMethod::Authnet, productVariants: \SellApp\Resource\CreateInvoiceRequestApplicationJsonPropertyProductVariants::fromArray($this->loadFixture('create_invoice_request_application_json_property_product_variants')));
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateInvoiceResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['customer_email']);
    }

    public function testSearch(): void
    {
        $fixture = $this->loadFixture('list_search_invoices_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->search(search: 'test_value', searchBy: \SellApp\Resource\InvoicesSearchBy::Default, id: 'test_value', email: 'test_value', transactionId: 'test_value', serialCode: 'test_value', additionalInfo: 'test_value', productName: 'test_value', discordData: 'test_value', cryptoTxid: 'test_value', cryptoAddress: 'test_value', couponCode: 'test_value', status: [], paymentMethods: [], sort: \SellApp\Resource\InvoicesSort::CreatedAt);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/search', $request->getUri()->getPath());
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_invoice_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->get(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetInvoiceResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1', $request->getUri()->getPath());
    }

    public function testGoToCheckout(): void
    {
        $fixture = $this->loadFixture('sdk_create_checkout_session_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->goToCheckout(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateCheckoutSessionResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/checkout', $request->getUri()->getPath());
    }

    public function testGetDeliverables(): void
    {
        $fixture = $this->loadFixture('sdk_get_invoice_deliverables_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->getDeliverables(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetInvoiceDeliverablesResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/deliverables', $request->getUri()->getPath());
    }

    public function testMarkCompleted(): void
    {
        $fixture = $this->loadFixture('sdk_mark_pending_invoice_completed_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->markCompleted(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkMarkPendingInvoiceCompletedResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/mark-completed', $request->getUri()->getPath());
    }

    public function testMarkVoided(): void
    {
        $fixture = $this->loadFixture('sdk_mark_pending_invoice_voided_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->markVoided(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/mark-voided', $request->getUri()->getPath());
    }

    public function testIssueReplacement(): void
    {
        $fixture = $this->loadFixture('sdk_issue_replacement_for_completed_invoice_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->issueReplacement(1, productVariants: \SellApp\Resource\IssueReplacementForCompletedInvoiceRequestApplicationJsonPropertyProductVariants::fromArray($this->loadFixture('issue_replacement_for_completed_invoice_request_application_json_property_product_variants')));
        $this->assertInstanceOf(\SellApp\Resource\SdkIssueReplacementForCompletedInvoiceResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/issue-replacement', $request->getUri()->getPath());
    }

    public function testUpdateStatus(): void
    {
        $fixture = $this->loadFixture('sdk_update_invoice_status_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->updateStatus(1, status: \SellApp\Resource\SdkUpdateOrderStatusRequestApplicationJsonStatus::Completed);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateInvoiceStatusResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/status', $request->getUri()->getPath());
    }

    public function testCreateRefund(): void
    {
        $fixture = $this->loadFixture('sdk_create_invoice_refund_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->createRefund(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateInvoiceRefundResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/refunds', $request->getUri()->getPath());
    }

    public function testRetryFulfillment(): void
    {
        $fixture = $this->loadFixture('sdk_create_fulfillment_retry_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->retryFulfillment(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateFulfillmentRetryResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/fulfillment-retries', $request->getUri()->getPath());
    }

    public function testRetryDynamicDelivery(): void
    {
        $fixture = $this->loadFixture('sdk_create_dynamic_delivery_retry_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->retryDynamicDelivery(1, deliveredProductId: 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateDynamicDeliveryRetryResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/dynamic-delivery-retries', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame(1, $body['delivered_product_id']);
    }

    public function testNotifyFulfillment(): void
    {
        $fixture = $this->loadFixture('sdk_create_fulfillment_notifications_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->notifyFulfillment(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateFulfillmentNotificationsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/invoices/1/fulfillment-notifications', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_invoices_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->invoices()->list();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
