<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class OrdersTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_list_orders_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->list(limit: 1, page: 1);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/orders', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sdk_create_order_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->create(customerEmail: 'test_value', paymentMethod: \SellApp\Resource\PaymentMethod::Authnet, productVariants: \SellApp\Resource\CreateOrderRequestApplicationJsonPropertyProductVariants::fromArray($this->loadFixture('create_order_request_application_json_property_product_variants')));
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateOrderResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['customer_email']);
    }

    public function testSearch(): void
    {
        $fixture = $this->loadFixture('list_search_orders_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->search(filters: [], sort: [], pagination: \SellApp\Resource\SearchOrdersRequestApplicationJsonPropertyPagination::fromArray($this->loadFixture('search_orders_request_application_json_property_pagination')));
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/search', $request->getUri()->getPath());
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_order_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->get(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetOrderResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1', $request->getUri()->getPath());
    }

    public function testUpdateStatus(): void
    {
        $fixture = $this->loadFixture('sdk_update_order_status_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->updateStatus(1, status: \SellApp\Resource\SdkUpdateOrderStatusRequestApplicationJsonStatus::Completed);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateOrderStatusResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/status', $request->getUri()->getPath());
    }

    public function testCreateCheckout(): void
    {
        $fixture = $this->loadFixture('sdk_create_order_checkout_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->createCheckout(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateOrderCheckoutResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/checkout', $request->getUri()->getPath());
    }

    public function testCreateReplacement(): void
    {
        $fixture = $this->loadFixture('sdk_create_order_replacement_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->createReplacement(1, productVariants: \SellApp\Resource\CreateOrderReplacementRequestApplicationJsonPropertyProductVariants::fromArray($this->loadFixture('create_order_replacement_request_application_json_property_product_variants')));
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateOrderReplacementResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/replacements', $request->getUri()->getPath());
    }

    public function testCreateRefund(): void
    {
        $fixture = $this->loadFixture('sdk_create_order_refund_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->createRefund(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateOrderRefundResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/refunds', $request->getUri()->getPath());
    }

    public function testRetryFulfillment(): void
    {
        $fixture = $this->loadFixture('sdk_retry_order_fulfillment_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->retryFulfillment(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkRetryOrderFulfillmentResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/fulfillment-retries', $request->getUri()->getPath());
    }

    public function testRetryDynamicDelivery(): void
    {
        $fixture = $this->loadFixture('sdk_retry_order_dynamic_delivery_response_value_202_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->retryDynamicDelivery(1, deliveredProductId: 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkRetryOrderDynamicDeliveryResponseValue202ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/dynamic-delivery-retries', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame(1, $body['delivered_product_id']);
    }

    public function testSendFulfillmentNotifications(): void
    {
        $fixture = $this->loadFixture('sdk_send_order_fulfillment_notifications_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->sendFulfillmentNotifications(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkSendOrderFulfillmentNotificationsResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/fulfillment-notifications', $request->getUri()->getPath());
    }

    public function testListDeliverables(): void
    {
        $fixture = $this->loadFixture('sdk_list_order_deliverables_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->listDeliverables(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkListOrderDeliverablesResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/deliverables', $request->getUri()->getPath());
    }

    public function testCreateFromWallet(): void
    {
        $fixture = $this->loadFixture('sdk_create_wallet_order_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->createFromWallet(customerEmail: 'test_value', productVariants: \SellApp\Resource\CreateWalletOrderRequestApplicationJsonPropertyProductVariants::fromArray($this->loadFixture('create_wallet_order_request_application_json_property_product_variants')));
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateWalletOrderResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/wallet', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['customer_email']);
    }

    public function testPayFromWallet(): void
    {
        $fixture = $this->loadFixture('sdk_pay_order_from_wallet_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->payFromWallet(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkPayOrderFromWalletResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/orders/1/wallet-payments', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_orders_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->orders()->list();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
