<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class ProductVariantsBookingTest extends TestCase
{
    use TestHelper;

    public function testListAvailability(): void
    {
        $fixture = $this->loadFixture('sdk_list_booking_availability_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsBooking()->listAvailability(1, 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkListBookingAvailabilityResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/booking/availability', $request->getUri()->getPath());
    }

    public function testCreateHold(): void
    {
        $fixture = $this->loadFixture('sdk_create_booking_hold_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsBooking()->createHold(1, 1, slotStartAt: new \DateTimeImmutable('2023-01-01T00:00:00Z'));
        $this->assertInstanceOf(\SellApp\Resource\SdkCreateBookingHoldResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/booking/holds', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('2023-01-01T00:00:00.000+00:00', $body['slot_start_at']);
    }

    public function testReleaseHold(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->productVariantsBooking()->releaseHold(1, 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/booking/holds/test_value', $request->getUri()->getPath());
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_booking_configuration_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsBooking()->get('test_value', 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetBookingConfigurationResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/products/test_value/variants/1/booking', $request->getUri()->getPath());
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_booking_configuration_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsBooking()->replace('test_value', 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceBookingConfigurationResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/products/test_value/variants/1/booking', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_booking_configuration_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsBooking()->update('test_value', 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateBookingConfigurationResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/products/test_value/variants/1/booking', $request->getUri()->getPath());
    }
}
