<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class ProductVariantsPricingTest extends TestCase
{
    use TestHelper;

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_product_variant_pricing_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsPricing()->replace(1, 1, pricing: \SellApp\Resource\ReplaceProductVariantPricingRequestApplicationJsonPropertyPricing::fromArray($this->loadFixture('replace_product_variant_pricing_request_application_json_property_pricing')), paymentMethods: []);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceProductVariantPricingResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/pricing', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_product_variant_pricing_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->productVariantsPricing()->update(1, 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdateProductVariantPricingResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/pricing', $request->getUri()->getPath());
    }
}
