<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class PromotionsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_sdk_list_promotions_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->list(limit: 1, page: 1, pagination: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
        $this->assertArrayHasKey('pagination', $query);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sdk_create_promotion_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->create(name: 'test_value', status: \SellApp\Resource\SdkCreatePromotionRequestApplicationJsonStatus::Active, priority: 1, isStackable: true, phases: [\SellApp\Resource\CreatePromotionRequestApplicationJsonPropertyPhasesItem::fromArray($this->loadFixture('create_promotion_request_application_json_property_phases_item'))]);
        $this->assertInstanceOf(\SellApp\Resource\SdkCreatePromotionResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['name']);
        $this->assertSame(1, $body['priority']);
        $this->assertTrue($body['is_stackable']);
    }

    public function testSearch(): void
    {
        $fixture = $this->loadFixture('list_sdk_search_promotions_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->search(filters: [], sort: [], search: \SellApp\Resource\SearchPromotionsRequestApplicationJsonPropertySearch::fromArray($this->loadFixture('search_promotions_request_application_json_property_search')), includes: [], limit: 1, page: 1, pagination: true);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/search', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
        $this->assertArrayHasKey('pagination', $query);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_promotion_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->get(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetPromotionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/1', $request->getUri()->getPath());
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_promotion_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->replace(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplacePromotionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/1', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('sdk_update_promotion_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->update(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkUpdatePromotionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/1', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->promotions()->delete(1);
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/1', $request->getUri()->getPath());
    }

    public function testRestore(): void
    {
        $fixture = $this->loadFixture('sdk_restore_promotion_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->restore(1, name: 'test_value', status: \SellApp\Resource\SdkCreatePromotionRequestApplicationJsonStatus::Active, priority: 1, isStackable: true, phases: [\SellApp\Resource\RestorePromotionRequestApplicationJsonPropertyPhasesItem::fromArray($this->loadFixture('restore_promotion_request_application_json_property_phases_item'))]);
        $this->assertInstanceOf(\SellApp\Resource\SdkRestorePromotionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/promotions/1/restore', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['name']);
        $this->assertSame(1, $body['priority']);
        $this->assertTrue($body['is_stackable']);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_sdk_list_promotions_response_value_200_application_json');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->promotions()->list();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
