<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class SubscriptionsTest extends TestCase
{
    use TestHelper;

    public function testCancel(): void
    {
        $fixture = $this->loadFixture('sdk_cancel_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->cancel(1, cancelAtPeriodEnd: true);
        $this->assertInstanceOf(\SellApp\Resource\SdkCancelSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/cancel', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertTrue($body['cancel_at_period_end']);
    }

    public function testGetCapabilities(): void
    {
        $fixture = $this->loadFixture('sdk_get_subscription_capabilities_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->getCapabilities(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetSubscriptionCapabilitiesResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/capabilities', $request->getUri()->getPath());
    }

    public function testCancelAtPeriodEnd(): void
    {
        $fixture = $this->loadFixture('sdk_cancel_subscription_at_period_end_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->cancelAtPeriodEnd(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCancelSubscriptionAtPeriodEndResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/cancel-period-end', $request->getUri()->getPath());
    }

    public function testCancelImmediately(): void
    {
        $fixture = $this->loadFixture('sdk_cancel_subscription_immediately_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->cancelImmediately(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkCancelSubscriptionImmediatelyResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/cancel-immediately', $request->getUri()->getPath());
    }

    public function testPause(): void
    {
        $fixture = $this->loadFixture('sdk_pause_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->pause(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkPauseSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/pause', $request->getUri()->getPath());
    }

    public function testResume(): void
    {
        $fixture = $this->loadFixture('sdk_resume_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->resume(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkResumeSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/resume', $request->getUri()->getPath());
    }

    public function testUpdatePaymentMethod(): void
    {
        $client = $this->createMockClient([['status' => 200, 'body' => []]]);
        $client->subscriptions()->updatePaymentMethod(1);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/update-payment-method', $request->getUri()->getPath());
    }

    public function testPreviewPlanChange(): void
    {
        $client = $this->createMockClient([['status' => 200, 'body' => []]]);
        $client->subscriptions()->previewPlanChange(1, targetVariantId: 1);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/change-plan/preview', $request->getUri()->getPath());
    }

    public function testConfirmPlanChange(): void
    {
        $client = $this->createMockClient([['status' => 200, 'body' => []]]);
        $client->subscriptions()->confirmPlanChange(1, targetVariantId: 1, previewToken: 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/change-plan/confirm', $request->getUri()->getPath());
    }

    public function testPreviewRenewalDate(): void
    {
        $fixture = $this->loadFixture('sdk_preview_subscription_renewal_date_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->previewRenewalDate(1, renewalDate: new \DateTimeImmutable('2023-01-01T00:00:00Z'));
        $this->assertInstanceOf(\SellApp\Resource\SdkPreviewSubscriptionRenewalDateChangeResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/change-renewal-date/preview', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('2023-01-01T00:00:00.000+00:00', $body['renewal_date']);
    }

    public function testConfirmRenewalDate(): void
    {
        $fixture = $this->loadFixture('sdk_confirm_subscription_renewal_date_change_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->confirmRenewalDate(1, renewalDate: new \DateTimeImmutable('2023-01-01T00:00:00Z'));
        $this->assertInstanceOf(\SellApp\Resource\SdkConfirmSubscriptionRenewalDateChangeResponseValue200ApplicationJson::class, $result);
        $this->assertSame($fixture['message'], $result->message);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1/actions/change-renewal-date/confirm', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('2023-01-01T00:00:00.000+00:00', $body['renewal_date']);
    }

    public function testListSubscriptions(): void
    {
        $fixture = $this->loadFixture('list_list_subscriptions_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->listSubscriptions();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions', $request->getUri()->getPath());
    }

    public function testSearchSubscriptions(): void
    {
        $fixture = $this->loadFixture('list_search_subscriptions_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->searchSubscriptions(search: 'test_value', status: 'test_value');
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/search', $request->getUri()->getPath());
    }

    public function testGetSubscription(): void
    {
        $fixture = $this->loadFixture('sdk_get_subscription_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->getSubscription(1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetSubscriptionResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/subscriptions/1', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_subscriptions_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->subscriptions()->listSubscriptions();
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
