<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class VariantSerialsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_list_variant_serial_inventory_response_value_200_application_json_property_data_item');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantSerials()->list(1, 1, search: 'test_value', limit: 1, page: 1);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/serials', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['search']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertArrayHasKey('page', $query);
    }

    public function testAppend(): void
    {
        $fixture = $this->loadFixture('sdk_append_variant_serial_inventory_response_value_201_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantSerials()->append(1, 1, serials: ['test_value']);
        $this->assertInstanceOf(\SellApp\Resource\SdkAppendVariantSerialInventoryResponseValue201ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/serials', $request->getUri()->getPath());
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_variant_serial_inventory_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantSerials()->replace(1, 1, serials: ['test_value']);
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceVariantSerialInventoryResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/serials', $request->getUri()->getPath());
    }

    public function testQueue(): void
    {
        $fixture = $this->loadFixture('sdk_queue_variant_serial_import_response_value_202_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantSerials()->queue(1, 1, file: 'test_value', parsingMode: \SellApp\Resource\SdkQueueVariantSerialImportRequestMultipartFormDataParsingMode::Comma);
        $this->assertInstanceOf(\SellApp\Resource\SdkQueueVariantSerialImportResponseValue202ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/serials/import', $request->getUri()->getPath());
        $this->assertStringContainsString('name="file"', (string) $request->getBody());
        $this->assertStringContainsString((string) 'test_value', (string) $request->getBody());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->variantSerials()->delete(1, 1, 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v2/products/1/variants/1/serials/test_value', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_list_variant_serial_inventory_response_value_200_application_json_property_data_item');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantSerials()->list(1, 1);
        $this->assertInstanceOf(\SellApp\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
