<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class VariantDeliverablesTest extends TestCase
{
    use TestHelper;

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sdk_get_variant_deliverable_configuration_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantDeliverables()->get('test_value', 1);
        $this->assertInstanceOf(\SellApp\Resource\SdkGetVariantDeliverableConfigurationResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v2/products/test_value/variants/1/deliverable', $request->getUri()->getPath());
    }

    public function testReplace(): void
    {
        $fixture = $this->loadFixture('sdk_replace_variant_deliverable_configuration_response_value_200_application_json');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->variantDeliverables()->replace('test_value', 1, types: [\SellApp\Resource\CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes::Downloadable], data: \SellApp\Resource\ReplaceVariantDeliverableConfigurationRequestApplicationJsonPropertyData::fromArray($this->loadFixture('replace_variant_deliverable_configuration_request_application_json_property_data')));
        $this->assertInstanceOf(\SellApp\Resource\SdkReplaceVariantDeliverableConfigurationResponseValue200ApplicationJson::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PUT', $request->getMethod());
        $this->assertStringEndsWith('v2/products/test_value/variants/1/deliverable', $request->getUri()->getPath());
    }
}
