<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\SdkCreateAddOnDraftResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetAddOnResponseValue200ApplicationJson;
use SellApp\Resource\SdkListAddOnsResponseValue200ApplicationJson;
use SellApp\Resource\SdkReplaceAddOnResponseValue200ApplicationJson;
use SellApp\Resource\SdkSearchAddOnsResponseValue200ApplicationJson;
use SellApp\Resource\SdkUpdateAddOnResponseValue200ApplicationJson;

class AddOns
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List add-ons
     *
     * Retrieve the store's add-ons with compact variant references and ordered parent-product assignments. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @param bool|null $pagination Set to false to return at most 100 matching items in one data array without pagination links or metadata. Defaults to true.
     * @param bool|null $withDrafts Include draft add-ons alongside published add-ons.
     * @param bool|null $onlyDrafts Return only draft add-ons.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SdkListAddOnsResponseValue200ApplicationJson>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?bool $pagination = null,
        ?bool $withDrafts = null,
        ?bool $onlyDrafts = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listAddOns', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
            'pagination' => $pagination,
            'with_drafts' => $withDrafts,
            'only_drafts' => $onlyDrafts,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/addons',
            query: $query,
            modelClass: SdkListAddOnsResponseValue200ApplicationJson::class,
            options: $options,
        );
    }

    /**
     * Create an add-on draft
     *
     * Create an add-on, optionally including its variant and parent_product_ids in one transaction. Set is_draft false with variant to publish immediately. Without variant, new add-ons remain drafts. Requires the listing API-key ability and store listing permission. Invalid variants or parent products roll back the complete creation. This call does not have response-replay idempotency; check for the created add-on before retrying a request whose response was lost. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $title Seller-facing title for the add-on.
     * @param string|null $slug Optional store-unique slug. When omitted during creation, SellApp generates one from the title.
     * @param string $description Description shown when the add-on is offered.
     * @param \SellApp\Resource\CatalogVisibility $visibility
     * @param bool|null $isDraft Defaults to true on creation. Set false to publish. Publication requires exactly one published, fixed-price, single-payment variant; creation can include that variant in the same request.
     * @param array<int>|null $parentProductIds Ordered IDs of same-store, non-subscription products, courses, or bookings to assign. Supplying the field replaces the complete assignment set.
     * @param \SellApp\Resource\CreateAddOnDraftRequestApplicationJsonPropertyVariant|null $variant
     * @return \SellApp\Resource\SdkCreateAddOnDraftResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function create(
        string $title,
        string $description,
        \SellApp\Resource\CatalogVisibility $visibility,
        ?string $slug = null,
        ?bool $isDraft = null,
        ?array $parentProductIds = null,
        ?\SellApp\Resource\CreateAddOnDraftRequestApplicationJsonPropertyVariant $variant = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateAddOnDraftResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createAddOnDraft', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'title' => $title,
            'slug' => $slug,
            'description' => $description,
            'visibility' => $visibility->value,
            'is_draft' => $isDraft,
            'parent_product_ids' => $parentProductIds,
            'variant' => $variant,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateAddOnDraftRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/addons',
            body: $body,
            options: $options,
        );
        return SdkCreateAddOnDraftResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Search add-ons
     *
     * Search add-ons by title, slug, or description and optionally filter or sort the result set. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param array<\SellApp\Resource\SearchAddOnsRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\SearchAddOnsRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\SearchAddOnsRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\SearchAddOnsRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @param bool|null $pagination Set to false to return at most 100 matching items in one data array without pagination links or metadata. Defaults to true.
     * @param bool|null $withDrafts Include draft add-ons alongside published add-ons.
     * @param bool|null $onlyDrafts Return only draft add-ons.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SdkSearchAddOnsResponseValue200ApplicationJson>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\SearchAddOnsRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?int $limit = null,
        ?int $page = null,
        ?bool $pagination = null,
        ?bool $withDrafts = null,
        ?bool $onlyDrafts = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchAddOns', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
            'pagination' => $pagination,
            'with_drafts' => $withDrafts,
            'only_drafts' => $onlyDrafts,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/addons/search',
            query: $query,
            modelClass: SdkSearchAddOnsResponseValue200ApplicationJson::class,
            options: $options,
        );
    }

    /**
     * Retrieve an add-on
     *
     * Retrieve one add-on owned by the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $addon The addon path parameter.
     * @param bool|null $pagination Set to false to return at most 100 matching items in one data array without pagination links or metadata. Defaults to true.
     * @param bool|null $withDrafts Include draft add-ons alongside published add-ons.
     * @param bool|null $onlyDrafts Return only draft add-ons.
     * @return \SellApp\Resource\SdkGetAddOnResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $addon,
        ?bool $pagination = null,
        ?bool $withDrafts = null,
        ?bool $onlyDrafts = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetAddOnResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getAddOn', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'pagination' => $pagination,
            'with_drafts' => $withDrafts,
            'only_drafts' => $onlyDrafts,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/addons/' . rawurlencode((string) $addon),
            query: $query,
            options: $options,
        );
        return SdkGetAddOnResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update an add-on
     *
     * Update an add-on and optionally replace its ordered parent-product assignments. Publication is rejected unless the add-on has exactly one published, fixed-price, single-payment variant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $addon The addon path parameter.
     * @param string|null $title Seller-facing title for the add-on.
     * @param string|null $slug Optional store-unique slug. When omitted during creation, SellApp generates one from the title.
     * @param string|null $description Description shown when the add-on is offered.
     * @param \SellApp\Resource\CatalogVisibility|null $visibility
     * @param bool|null $isDraft Defaults to true on creation. Set false to publish. Publication requires exactly one published, fixed-price, single-payment variant; creation can include that variant in the same request.
     * @param array<int>|null $parentProductIds Ordered IDs of same-store, non-subscription products, courses, or bookings to assign. Supplying the field replaces the complete assignment set.
     * @return \SellApp\Resource\SdkReplaceAddOnResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function replace(
        int $addon,
        ?string $title = null,
        ?string $slug = null,
        ?string $description = null,
        ?\SellApp\Resource\CatalogVisibility $visibility = null,
        ?bool $isDraft = null,
        ?array $parentProductIds = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkReplaceAddOnResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'replaceAddOn', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'title' => $title,
            'slug' => $slug,
            'description' => $description,
            'visibility' => $visibility?->value,
            'is_draft' => $isDraft,
            'parent_product_ids' => $parentProductIds,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkReplaceAddOnRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/addons/' . rawurlencode((string) $addon),
            body: $body,
            options: $options,
        );
        return SdkReplaceAddOnResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update an add-on
     *
     * Update an add-on and optionally replace its ordered parent-product assignments. Publication is rejected unless the add-on has exactly one published, fixed-price, single-payment variant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $addon The addon path parameter.
     * @param string|null $title Seller-facing title for the add-on.
     * @param string|null $slug Optional store-unique slug. When omitted during creation, SellApp generates one from the title.
     * @param string|null $description Description shown when the add-on is offered.
     * @param \SellApp\Resource\CatalogVisibility|null $visibility
     * @param bool|null $isDraft Defaults to true on creation. Set false to publish. Publication requires exactly one published, fixed-price, single-payment variant; creation can include that variant in the same request.
     * @param array<int>|null $parentProductIds Ordered IDs of same-store, non-subscription products, courses, or bookings to assign. Supplying the field replaces the complete assignment set.
     * @return \SellApp\Resource\SdkUpdateAddOnResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function update(
        int $addon,
        ?string $title = null,
        ?string $slug = null,
        ?string $description = null,
        ?\SellApp\Resource\CatalogVisibility $visibility = null,
        ?bool $isDraft = null,
        ?array $parentProductIds = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkUpdateAddOnResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'updateAddOn', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'title' => $title,
            'slug' => $slug,
            'description' => $description,
            'visibility' => $visibility?->value,
            'is_draft' => $isDraft,
            'parent_product_ids' => $parentProductIds,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkReplaceAddOnRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/addons/' . rawurlencode((string) $addon),
            body: $body,
            options: $options,
        );
        return SdkUpdateAddOnResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Delete an add-on
     *
     * Soft-delete an add-on and remove its product assignments. The deleted resource is returned for audit and reconciliation workflows. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $addon The addon path parameter.
     * @return void
     * @throws \SellApp\Exception\SDKException
     */
    public function delete(
        int $addon,
        ?\SellApp\RequestOptions $options = null,
    ): void {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'deleteAddOn', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $this->client->request(
            method: 'DELETE',
            path: 'v2/addons/' . rawurlencode((string) $addon),
            options: $options,
        );
    }
}
