<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkGetAffiliateReferralSessionResponseValue200ApplicationJson;

class AffiliateReferralSessions
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List affiliate referral sessions
     *
     * List store-scoped referral attribution sessions. Session identifiers are sensitive. Requires `affiliate` and `affiliate:sensitive`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $affiliateId Filter by affiliate ID.
     * @param bool|null $active Return active or expired sessions.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $affiliateId = null,
        ?bool $active = null,
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listAffiliateReferralSessions', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'affiliate_id' => $affiliateId,
            'active' => $active,
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/affiliate-referral-sessions',
            query: $query,
            modelClass: ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve an affiliate referral session
     *
     * Retrieve one store-scoped referral attribution session. Requires `affiliate` and `affiliate:sensitive`. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $referralSession The referralSession path parameter.
     * @return \SellApp\Resource\SdkGetAffiliateReferralSessionResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $referralSession,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetAffiliateReferralSessionResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getAffiliateReferralSession', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/affiliate-referral-sessions/' . rawurlencode((string) $referralSession),
            options: $options,
        );
        return SdkGetAffiliateReferralSessionResponseValue200ApplicationJson::fromArray($response);
    }
}
