<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\SdkRecordCreditTransactionResponseValue200ApplicationJson;

class Credits
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * Record a credit transaction
     *
     * Atomically grant, consume, or administratively adjust integer credit units. Reusing the same idempotency key with the same transaction is a no-op; conflicting reuse is rejected. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $customerId
     * @param int $productId
     * @param \SellApp\Resource\SdkRecordCreditTransactionRequestApplicationJsonKind $kind
     * @param int $amountUnits The signed amount of credit units. Must not be zero.
     * @param string $idempotencyKey
     * @param string|null $reason
     * @param string|null $sourceType
     * @param string|null $sourceId
     * @param \SellApp\Resource\RecordCreditTransactionRequestApplicationJsonPropertyMetadata|null $metadata
     * @return \SellApp\Resource\SdkRecordCreditTransactionResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function record(
        int $customerId,
        int $productId,
        \SellApp\Resource\SdkRecordCreditTransactionRequestApplicationJsonKind $kind,
        int $amountUnits,
        string $idempotencyKey,
        ?string $reason = null,
        ?string $sourceType = null,
        ?string $sourceId = null,
        ?\SellApp\Resource\RecordCreditTransactionRequestApplicationJsonPropertyMetadata $metadata = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkRecordCreditTransactionResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'recordCreditTransaction', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'customer_id' => $customerId,
            'product_id' => $productId,
            'kind' => $kind->value,
            'amount_units' => $amountUnits,
            'idempotency_key' => $idempotencyKey,
            'reason' => $reason,
            'source_type' => $sourceType,
            'source_id' => $sourceId,
            'metadata' => $metadata,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkRecordCreditTransactionRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/credit-transactions',
            body: $body,
            options: $options,
        );
        return SdkRecordCreditTransactionResponseValue200ApplicationJson::fromArray($response);
    }
}
