<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListExportsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkCreateExportResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetExportResponseValue200ApplicationJson;

class Exports
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List exports
     *
     * List permitted exports, 50 per page. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request. Sales, tax and customer reports require invoice store permission. Affiliate payout reports require affiliate and affiliate:payout permissions. The category selects the applicable permission checks; listing returns only authorized categories.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListExportsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function listExports(
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listExports', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/exports',
            modelClass: ListExportsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Create an export
     *
     * Create a queued sales, tax, customer or affiliate payout report. One export may be queued or running per store, and two per requesting account across all credentials and stores. When capacity is full, HTTP 429 includes Retry-After: 60; poll the existing export and wait before creating another. Date ranges include both end dates and may span at most 366 calendar days. Omitted or null to defaults to today; omitted or null from defaults to 365 days before to. Sales and tax use sale update dates; customers and affiliate payouts use creation dates. Reports are limited to 10,000 source rows, 5 MiB of serialized source data and a 10 MiB output file. Tax summaries count source sales toward these limits. A report that exceeds a limit fails without publishing a partial file; request a smaller date range. Jobs may wait up to 15 minutes to start and run for at most 60 seconds. The requesting actor is recorded but is not returned in this response. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request. Sales, tax and customer reports require invoice store permission. Affiliate payout reports require affiliate and affiliate:payout permissions. The category selects the applicable permission checks; listing returns only authorized categories.
     * @param \SellApp\Resource\SdkCreateExportRequestApplicationJsonType $type
     * @param \SellApp\Resource\SdkCreateExportRequestApplicationJsonFormat $format
     * @param \SellApp\Resource\CreateExportRequestApplicationJsonPropertyParameters|null $parameters
     * @return \SellApp\Resource\SdkCreateExportResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function createExport(
        \SellApp\Resource\SdkCreateExportRequestApplicationJsonType $type,
        \SellApp\Resource\SdkCreateExportRequestApplicationJsonFormat $format,
        ?\SellApp\Resource\CreateExportRequestApplicationJsonPropertyParameters $parameters = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateExportResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(true, 'createExport', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'type' => $type->value,
            'format' => $format->value,
            'parameters' => $parameters,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateExportRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/exports',
            body: $body,
            options: $options,
        );
        return SdkCreateExportResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Retrieve an export
     *
     * Poll until completed, failed, or expired. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request. Sales, tax and customer reports require invoice store permission. Affiliate payout reports require affiliate and affiliate:payout permissions. The category selects the applicable permission checks; listing returns only authorized categories.
     * @param string $export The export identifier.
     * @return \SellApp\Resource\SdkGetExportResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function getExport(
        string $export,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetExportResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getExport', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/exports/' . rawurlencode((string) $export),
            options: $options,
        );
        return SdkGetExportResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Download an export
     *
     * Validate the five-minute signed API URL, then redirect to a short-lived private object-storage URL. The API does not stream the file. Pending or running exports return 409; expired exports return 410. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request. Sales, tax and customer reports require invoice store permission. Affiliate payout reports require affiliate and affiliate:payout permissions. The category selects the applicable permission checks; listing returns only authorized categories.
     * @param string $export The export identifier.
     * @param int $expires Expiry timestamp from the generated download URL.
     * @param string $signature Copy the signature from the response-supplied download_url. The example is illustrative and cannot authorize a download.
     * @return mixed
     * @throws \SellApp\Exception\SDKException
     */
    public function downloadExport(
        string $export,
        int $expires,
        string $signature,
        ?\SellApp\RequestOptions $options = null,
    ): mixed {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'downloadExport', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = [
            'expires' => $expires,
            'signature' => $signature,
        ];
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/exports/' . rawurlencode((string) $export) . '/download',
            query: $query,
            options: $options,
        );
        return $response;
    }
}
