<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListFeedbackResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkGetFeedbackResponseValue200ApplicationJson;
use SellApp\Resource\SdkReplyToFeedbackResponseValue200ApplicationJson;
use SellApp\Resource\SdkV2GetFeedbackResponseValue200ApplicationJson;
use SellApp\Resource\SdkV2ReplaceFeedbackResponseValue200ApplicationJson;
use SellApp\Resource\SdkV2ReplyToFeedbackResponseValue200ApplicationJson;
use SellApp\Resource\SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\V2ListFeedbackResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\V2SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem;

class Feedback
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List all feedback
     *
     * List customer feedback for your store, 15 entries per page by default.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListFeedbackResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/feedback',
            query: $query,
            modelClass: ListFeedbackResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve specific feedback
     *
     * Retrieve a customer's feedback by its ID.
     * @param int $feedback The feedback path parameter.
     * @return \SellApp\Resource\SdkGetFeedbackResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $feedback,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetFeedbackResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/feedback/' . rawurlencode((string) $feedback),
            options: $options,
        );
        return SdkGetFeedbackResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Reply to feedback
     *
     * Publish a seller reply to a customer's feedback.
     * @param int $feedback The feedback path parameter.
     * @param string $reply
     * @return \SellApp\Resource\SdkReplyToFeedbackResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function reply(
        int $feedback,
        string $reply,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkReplyToFeedbackResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'replyToFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'reply' => $reply,
        ];
        \SellApp\Resource\SdkReplyToFeedbackRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/feedback/' . rawurlencode((string) $feedback),
            body: $body,
            options: $options,
        );
        return SdkReplyToFeedbackResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Search feedback
     *
     * Search feedback using JSON body filters, search terms, includes, and sort instructions.
     * @param array<\SellApp\Resource\SearchFeedbackRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\SearchFeedbackRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\SearchFeedbackRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\SearchFeedbackRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\SearchFeedbackRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v1/feedback/search',
            modelClass: SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * List all feedback
     *
     * List customer feedback for your store, 15 entries per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\V2ListFeedbackResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function v2ListFeedback(
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2ListFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/feedback',
            query: $query,
            modelClass: V2ListFeedbackResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Search feedback
     *
     * Search feedback using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param array<\SellApp\Resource\V2SearchFeedbackRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\V2SearchFeedbackRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\V2SearchFeedbackRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\V2SearchFeedbackRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\V2SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function v2SearchFeedback(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\V2SearchFeedbackRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2SearchFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/feedback/search',
            modelClass: V2SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve specific feedback
     *
     * Retrieve a customer's feedback by its ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $feedback The feedback path parameter.
     * @return \SellApp\Resource\SdkV2GetFeedbackResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function v2GetFeedback(
        int $feedback,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkV2GetFeedbackResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2GetFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/feedback/' . rawurlencode((string) $feedback),
            options: $options,
        );
        return SdkV2GetFeedbackResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Reply to feedback
     *
     * Publish a seller reply to a customer's feedback. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $feedback The feedback path parameter.
     * @param string $reply
     * @return \SellApp\Resource\SdkV2ReplaceFeedbackResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function v2ReplaceFeedback(
        int $feedback,
        string $reply,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkV2ReplaceFeedbackResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2ReplaceFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'reply' => $reply,
        ];
        \SellApp\Resource\SdkV2ReplaceFeedbackRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/feedback/' . rawurlencode((string) $feedback),
            body: $body,
            options: $options,
        );
        return SdkV2ReplaceFeedbackResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Reply to feedback
     *
     * Publish a seller reply to a customer's feedback. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $feedback The feedback path parameter.
     * @param string $reply
     * @return \SellApp\Resource\SdkV2ReplyToFeedbackResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function v2ReplyToFeedback(
        int $feedback,
        string $reply,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkV2ReplyToFeedbackResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2ReplyToFeedback', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'reply' => $reply,
        ];
        \SellApp\Resource\SdkV2ReplyToFeedbackRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/feedback/' . rawurlencode((string) $feedback),
            body: $body,
            options: $options,
        );
        return SdkV2ReplyToFeedbackResponseValue200ApplicationJson::fromArray($response);
    }
}
