<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListInvoicesResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkCreateCheckoutSessionResponseValue200ApplicationJson;
use SellApp\Resource\SdkCreateDynamicDeliveryRetryResponseValue200ApplicationJson;
use SellApp\Resource\SdkCreateFulfillmentNotificationsResponseValue200ApplicationJson;
use SellApp\Resource\SdkCreateFulfillmentRetryResponseValue200ApplicationJson;
use SellApp\Resource\SdkCreateInvoiceRefundResponseValue200ApplicationJson;
use SellApp\Resource\SdkCreateInvoiceResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetInvoiceDeliverablesResponseValue200ApplicationJson;
use SellApp\Resource\SdkGetInvoiceResponseValue200ApplicationJson;
use SellApp\Resource\SdkIssueReplacementForCompletedInvoiceResponseValue200ApplicationJson;
use SellApp\Resource\SdkMarkPendingInvoiceCompletedResponseValue200ApplicationJson;
use SellApp\Resource\SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson;
use SellApp\Resource\SdkUpdateInvoiceStatusResponseValue200ApplicationJson;
use SellApp\Resource\SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem;

class Invoices
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List all invoices
     *
     * List your store's invoices, 15 per page by default. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @param string|null $search Free-text search term.
     * @param \SellApp\Resource\InvoicesSearchBy|null $searchBy Which invoice field the search term should be matched against.
     * @param string|null $id Filter by invoice ID.
     * @param string|null $email Filter by customer email.
     * @param string|null $transactionId Filter by payment transaction ID.
     * @param string|null $serialCode Filter by delivered serial.
     * @param string|null $additionalInfo Filter by customer-provided additional information.
     * @param string|null $productName Filter by product or variant title.
     * @param string|null $discordData Filter by attached Discord data.
     * @param string|null $cryptoTxid Filter by crypto TXID.
     * @param string|null $cryptoAddress Filter by crypto payment address.
     * @param string|null $couponCode Filter by coupon code.
     * @param array<\SellApp\Resource\Status>|null $status Filter by one or more invoice statuses.
     * @param array<\SellApp\Resource\PaymentMethod>|null $paymentMethods Filter by one or more payment methods.
     * @param \SellApp\Resource\InvoicesSort|null $sort Sort order for the result set.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListInvoicesResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?string $search = null,
        ?\SellApp\Resource\InvoicesSearchBy $searchBy = null,
        ?string $id = null,
        ?string $email = null,
        ?string $transactionId = null,
        ?string $serialCode = null,
        ?string $additionalInfo = null,
        ?string $productName = null,
        ?string $discordData = null,
        ?string $cryptoTxid = null,
        ?string $cryptoAddress = null,
        ?string $couponCode = null,
        ?array $status = null,
        ?array $paymentMethods = null,
        ?\SellApp\Resource\InvoicesSort $sort = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listInvoices', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
            'search' => $search,
            'search_by' => $searchBy?->value,
            'id' => $id,
            'email' => $email,
            'transaction_id' => $transactionId,
            'serial_code' => $serialCode,
            'additional_info' => $additionalInfo,
            'product_name' => $productName,
            'discord_data' => $discordData,
            'crypto_txid' => $cryptoTxid,
            'crypto_address' => $cryptoAddress,
            'coupon_code' => $couponCode,
            'status' => $status,
            'payment_methods' => $paymentMethods,
            'sort' => $sort?->value,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/invoices',
            query: $query,
            modelClass: ListInvoicesResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Create an invoice
     *
     * Create an invoice for one or more product variants. Credit products are direct-only: send a credits variant by itself, use a quantity covered by its credit rate tiers, and respect the variant quantity increment rules. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $customerEmail
     * @param string|null $customerIp
     * @param \SellApp\Resource\PaymentMethod $paymentMethod
     * @param string|null $coupon
     * @param string|null $vatId
     * @param string|null $country
     * @param string|null $affiliate
     * @param \SellApp\Resource\CreateInvoiceRequestApplicationJsonPropertyExtra|null $extra
     * @param \SellApp\Resource\CreateInvoiceRequestApplicationJsonPropertyProductVariants $productVariants
     * @return \SellApp\Resource\SdkCreateInvoiceResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function create(
        string $customerEmail,
        \SellApp\Resource\PaymentMethod $paymentMethod,
        \SellApp\Resource\CreateInvoiceRequestApplicationJsonPropertyProductVariants $productVariants,
        ?string $customerIp = null,
        ?string $coupon = null,
        ?string $vatId = null,
        ?string $country = null,
        ?string $affiliate = null,
        ?\SellApp\Resource\CreateInvoiceRequestApplicationJsonPropertyExtra $extra = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateInvoiceResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createInvoice', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'customer_email' => $customerEmail,
            'customer_ip' => $customerIp,
            'payment_method' => $paymentMethod->value,
            'coupon' => $coupon,
            'vat_id' => $vatId,
            'country' => $country,
            'affiliate' => $affiliate,
            'extra' => $extra,
            'product_variants' => $productVariants,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateInvoiceRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices',
            body: $body,
            options: $options,
        );
        return SdkCreateInvoiceResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Search invoices
     *
     * Search invoices with the same filters as the list endpoint, sent in a JSON body instead of query parameters. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string|null $search
     * @param \SellApp\Resource\InvoicesSearchBy|null $searchBy
     * @param string|null $id
     * @param string|null $email
     * @param string|null $transactionId
     * @param string|null $serialCode
     * @param string|null $additionalInfo
     * @param string|null $productName
     * @param string|null $discordData
     * @param string|null $cryptoTxid
     * @param string|null $cryptoAddress
     * @param string|null $couponCode
     * @param array<\SellApp\Resource\Status>|null $status
     * @param array<\SellApp\Resource\PaymentMethod>|null $paymentMethods
     * @param \SellApp\Resource\InvoicesSort|null $sort
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?string $search = null,
        ?\SellApp\Resource\InvoicesSearchBy $searchBy = null,
        ?string $id = null,
        ?string $email = null,
        ?string $transactionId = null,
        ?string $serialCode = null,
        ?string $additionalInfo = null,
        ?string $productName = null,
        ?string $discordData = null,
        ?string $cryptoTxid = null,
        ?string $cryptoAddress = null,
        ?string $couponCode = null,
        ?array $status = null,
        ?array $paymentMethods = null,
        ?\SellApp\Resource\InvoicesSort $sort = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchInvoices', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/invoices/search',
            modelClass: SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve an invoice
     *
     * Retrieve an invoice by its ID to check its current payment and delivery state. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @return \SellApp\Resource\SdkGetInvoiceResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $invoice,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetInvoiceResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getInvoice', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/invoices/' . rawurlencode((string) $invoice),
            options: $options,
        );
        return SdkGetInvoiceResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Create a checkout session
     *
     * Create or reuse a payment session for a pending invoice. Create the invoice first, then send the customer to the returned top-level `payment_url`. A zero-priced checkout can return a paid invoice without a URL; delivery may still be queued. Check for a URL before redirecting and verify payment through signed events or a fresh read. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @return \SellApp\Resource\SdkCreateCheckoutSessionResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function goToCheckout(
        int $invoice,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateCheckoutSessionResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createCheckoutSession', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/checkout',
            options: $options,
        );
        return SdkCreateCheckoutSessionResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * View invoice deliverables
     *
     * Retrieve the deliverables sent to the customer, including each product in a multi-product purchase. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @return \SellApp\Resource\SdkGetInvoiceDeliverablesResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function getDeliverables(
        int $invoice,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetInvoiceDeliverablesResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getInvoiceDeliverables', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/deliverables',
            options: $options,
        );
        return SdkGetInvoiceDeliverablesResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Mark pending invoice completed
     *
     * Mark a pending invoice completed and start the normal delivery flow. SellApp normally handles completion after payment is confirmed. Use this only after independently confirming payment or deliberately authorizing delivery without it; the action can release purchased products. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param \SellApp\Resource\ExpectedStatus|null $expectedStatus Optional optimistic-concurrency guard. The mutation fails when the current order status no longer matches this value.
     * @return \SellApp\Resource\SdkMarkPendingInvoiceCompletedResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function markCompleted(
        int $invoice,
        ?\SellApp\Resource\ExpectedStatus $expectedStatus = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkMarkPendingInvoiceCompletedResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'markPendingInvoiceCompleted', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'expected_status' => $expectedStatus?->value,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkMarkPendingInvoiceCompletedRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/mark-completed',
            body: $body,
            options: $options,
        );
        return SdkMarkPendingInvoiceCompletedResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Mark pending invoice voided
     *
     * Void a pending invoice so it does not proceed to product delivery. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param \SellApp\Resource\ExpectedStatus|null $expectedStatus Optional optimistic-concurrency guard. The mutation fails when the current order status no longer matches this value.
     * @return \SellApp\Resource\SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function markVoided(
        int $invoice,
        ?\SellApp\Resource\ExpectedStatus $expectedStatus = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'markPendingInvoiceVoided', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'expected_status' => $expectedStatus?->value,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkMarkPendingInvoiceVoidedRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/mark-voided',
            body: $body,
            options: $options,
        );
        return SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Issue replacement for completed invoice
     *
     * Issue replacement deliverables for a completed purchase. This creates a new invoice and marks it completed, then starts the normal delivery and sales-notification flow. It is not just an edit to the old delivery. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param \SellApp\Resource\IssueReplacementForCompletedInvoiceRequestApplicationJsonPropertyProductVariants $productVariants
     * @return \SellApp\Resource\SdkIssueReplacementForCompletedInvoiceResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function issueReplacement(
        int $invoice,
        \SellApp\Resource\IssueReplacementForCompletedInvoiceRequestApplicationJsonPropertyProductVariants $productVariants,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkIssueReplacementForCompletedInvoiceResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'issueReplacementForCompletedInvoice', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'product_variants' => $productVariants,
        ];
        \SellApp\Resource\SdkIssueReplacementForCompletedInvoiceRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/issue-replacement',
            body: $body,
            options: $options,
        );
        return SdkIssueReplacementForCompletedInvoiceResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update invoice status
     *
     * Change a purchase through the invoice compatibility operation. Set status to COMPLETED, VOIDED, REVIEW, or DISPUTING. Dispute transitions schedule community-access revocation and a dispute webhook. Requires the `invoice` credential ability and store ownership. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param \SellApp\Resource\SdkUpdateOrderStatusRequestApplicationJsonStatus $status
     * @param \SellApp\Resource\ExpectedStatus|null $expectedStatus Optional optimistic-concurrency guard. The mutation fails when the current order status no longer matches this value.
     * @return \SellApp\Resource\SdkUpdateInvoiceStatusResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function updateStatus(
        int $invoice,
        \SellApp\Resource\SdkUpdateOrderStatusRequestApplicationJsonStatus $status,
        ?\SellApp\Resource\ExpectedStatus $expectedStatus = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkUpdateInvoiceStatusResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'updateInvoiceStatus', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'status' => $status->value,
            'expected_status' => $expectedStatus?->value,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkUpdateInvoiceStatusRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/status',
            body: $body,
            options: $options,
        );
        return SdkUpdateInvoiceStatusResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Create invoice refund
     *
     * Request a full or partial provider refund using the same idempotent refund ledger as the dashboard. Amounts are decimal currency strings, never floating-point numbers. Requires the `invoice` token ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param string|null $amount Optional partial refund amount in major currency units. Omit for the full remaining refundable amount.
     * @return \SellApp\Resource\SdkCreateInvoiceRefundResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function createRefund(
        int $invoice,
        ?string $amount = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateInvoiceRefundResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createInvoiceRefund', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'amount' => $amount,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateInvoiceRefundRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/refunds',
            body: $body,
            options: $options,
        );
        return SdkCreateInvoiceRefundResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Create fulfillment retry
     *
     * Retry failed delivery steps for a paid or partially fulfilled purchase. Repeated requests retry the same failed steps without creating duplicate work. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param string|null $email Optional replacement delivery email.
     * @return \SellApp\Resource\SdkCreateFulfillmentRetryResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function retryFulfillment(
        int $invoice,
        ?string $email = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateFulfillmentRetryResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createFulfillmentRetry', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'email' => $email,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateFulfillmentRetryRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/fulfillment-retries',
            body: $body,
            options: $options,
        );
        return SdkCreateFulfillmentRetryResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Create dynamic delivery retry
     *
     * Retry one same-store dynamic delivered product after validating order, line-item, variant, and webhook ownership. Callers should avoid concurrent retries for the same delivered product. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param int $deliveredProductId
     * @return \SellApp\Resource\SdkCreateDynamicDeliveryRetryResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function retryDynamicDelivery(
        int $invoice,
        int $deliveredProductId,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateDynamicDeliveryRetryResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createDynamicDeliveryRetry', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'delivered_product_id' => $deliveredProductId,
        ];
        \SellApp\Resource\SdkCreateDynamicDeliveryRetryRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/dynamic-delivery-retries',
            body: $body,
            options: $options,
        );
        return SdkCreateDynamicDeliveryRetryResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Create fulfillment notifications
     *
     * Resend fulfillment notifications for all or selected same-store product variants on a completed invoice. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $invoice The invoice path parameter.
     * @param string|null $email
     * @param array<int>|null $productVariantIds
     * @return \SellApp\Resource\SdkCreateFulfillmentNotificationsResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function notifyFulfillment(
        int $invoice,
        ?string $email = null,
        ?array $productVariantIds = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateFulfillmentNotificationsResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createFulfillmentNotifications', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'email' => $email,
            'product_variant_ids' => $productVariantIds,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateFulfillmentNotificationsRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/invoices/' . rawurlencode((string) $invoice) . '/fulfillment-notifications',
            body: $body,
            options: $options,
        );
        return SdkCreateFulfillmentNotificationsResponseValue200ApplicationJson::fromArray($response);
    }
}
