<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListLicenseInstancesResponseValue200ApplicationJsonPropertyDataItem;

class LicenseInstances
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List all license instances
     *
     * Retrieve a paginated list of license instances across your store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListLicenseInstancesResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listLicenseInstances', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/license-key-instances',
            query: $query,
            modelClass: ListLicenseInstancesResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }
}
