<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\SdkCreateRewardRuleResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetRewardRuleResponseValue200ApplicationJson;
use SellApp\Resource\SdkListRewardRulesResponseValue200ApplicationJson;
use SellApp\Resource\SdkReplaceRewardRuleResponseValue200ApplicationJson;
use SellApp\Resource\SdkSearchRewardRulesResponseValue200ApplicationJson;
use SellApp\Resource\SdkUpdateRewardRuleResponseValue200ApplicationJson;

class RewardRules
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List reward rules
     *
     * List reward rules owned by the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @param bool|null $pagination Set to false to return at most 100 matching items in one data array without pagination links or metadata. Defaults to true.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SdkListRewardRulesResponseValue200ApplicationJson>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?bool $pagination = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listRewardRules', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
            'pagination' => $pagination,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/reward-rules',
            query: $query,
            modelClass: SdkListRewardRulesResponseValue200ApplicationJson::class,
            options: $options,
        );
    }

    /**
     * Create a reward rule
     *
     * Create reward rule configuration. Grant issuance remains a separate operation. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $name
     * @param string|null $description
     * @param bool $isActive
     * @param \SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType $triggerType
     * @param int $triggerThreshold
     * @param array<\SellApp\Resource\CreateRewardRuleRequestApplicationJsonPropertyOutputsItem> $outputs
     * @param \DateTimeImmutable|null $expectedUpdatedAt
     * @return \SellApp\Resource\SdkCreateRewardRuleResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function create(
        string $name,
        bool $isActive,
        \SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType $triggerType,
        int $triggerThreshold,
        array $outputs,
        ?string $description = null,
        ?\DateTimeImmutable $expectedUpdatedAt = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateRewardRuleResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createRewardRule', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'is_active' => $isActive,
            'trigger_type' => $triggerType->value,
            'trigger_threshold' => $triggerThreshold,
            'outputs' => $outputs,
            'expected_updated_at' => $expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateRewardRuleRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/reward-rules',
            body: $body,
            options: $options,
        );
        return SdkCreateRewardRuleResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Search reward rules
     *
     * Search and filter reward rules owned by the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param array<\SellApp\Resource\SearchRewardRulesRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\SearchRewardRulesRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\SearchRewardRulesRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\SearchRewardRulesRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @param bool|null $pagination Set to false to return at most 100 matching items in one data array without pagination links or metadata. Defaults to true.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SdkSearchRewardRulesResponseValue200ApplicationJson>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\SearchRewardRulesRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?int $limit = null,
        ?int $page = null,
        ?bool $pagination = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchRewardRules', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
            'pagination' => $pagination,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/reward-rules/search',
            query: $query,
            modelClass: SdkSearchRewardRulesResponseValue200ApplicationJson::class,
            options: $options,
        );
    }

    /**
     * Retrieve a reward rule
     *
     * Retrieve one store-owned reward rule. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $rewardRule The rewardRule path parameter.
     * @return \SellApp\Resource\SdkGetRewardRuleResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $rewardRule,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetRewardRuleResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getRewardRule', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/reward-rules/' . rawurlencode((string) $rewardRule),
            options: $options,
        );
        return SdkGetRewardRuleResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update a reward rule
     *
     * Update reward rule configuration without directly issuing a customer grant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $rewardRule The rewardRule path parameter.
     * @param string|null $name
     * @param string|null $description
     * @param bool|null $isActive
     * @param \SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType|null $triggerType
     * @param int|null $triggerThreshold
     * @param array<\SellApp\Resource\ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem>|null $outputs
     * @param \DateTimeImmutable|null $expectedUpdatedAt
     * @return \SellApp\Resource\SdkReplaceRewardRuleResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function replace(
        int $rewardRule,
        ?string $name = null,
        ?string $description = null,
        ?bool $isActive = null,
        ?\SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType $triggerType = null,
        ?int $triggerThreshold = null,
        ?array $outputs = null,
        ?\DateTimeImmutable $expectedUpdatedAt = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkReplaceRewardRuleResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'replaceRewardRule', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'is_active' => $isActive,
            'trigger_type' => $triggerType?->value,
            'trigger_threshold' => $triggerThreshold,
            'outputs' => $outputs,
            'expected_updated_at' => $expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkReplaceRewardRuleRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/reward-rules/' . rawurlencode((string) $rewardRule),
            body: $body,
            options: $options,
        );
        return SdkReplaceRewardRuleResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update a reward rule
     *
     * Update reward rule configuration without directly issuing a customer grant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $rewardRule The rewardRule path parameter.
     * @param string|null $name
     * @param string|null $description
     * @param bool|null $isActive
     * @param \SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType|null $triggerType
     * @param int|null $triggerThreshold
     * @param array<\SellApp\Resource\UpdateRewardRuleRequestApplicationJsonPropertyOutputsItem>|null $outputs
     * @param \DateTimeImmutable|null $expectedUpdatedAt
     * @return \SellApp\Resource\SdkUpdateRewardRuleResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function update(
        int $rewardRule,
        ?string $name = null,
        ?string $description = null,
        ?bool $isActive = null,
        ?\SellApp\Resource\SdkCreateRewardRuleRequestApplicationJsonTriggerType $triggerType = null,
        ?int $triggerThreshold = null,
        ?array $outputs = null,
        ?\DateTimeImmutable $expectedUpdatedAt = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkUpdateRewardRuleResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'updateRewardRule', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'name' => $name,
            'description' => $description,
            'is_active' => $isActive,
            'trigger_type' => $triggerType?->value,
            'trigger_threshold' => $triggerThreshold,
            'outputs' => $outputs,
            'expected_updated_at' => $expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkUpdateRewardRuleRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/reward-rules/' . rawurlencode((string) $rewardRule),
            body: $body,
            options: $options,
        );
        return SdkUpdateRewardRuleResponseValue200ApplicationJson::fromArray($response);
    }
}
