<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\SdkConnectCustomDomainResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetCustomDomainResponseValue200ApplicationJson;
use SellApp\Resource\SdkListCustomDomainsResponseValue200ApplicationJson;
use SellApp\Resource\SdkRefreshCustomDomainStatusResponseValue200ApplicationJson;

class StoreCustomDomains
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List custom domains
     *
     * List the current store's custom-domain connection states and DNS verification records. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @return \SellApp\Resource\SdkListCustomDomainsResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkListCustomDomainsResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listCustomDomains', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/store/custom-domains',
            options: $options,
        );
        return SdkListCustomDomainsResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Connect a custom domain
     *
     * Connect a hostname through SellApp's managed Cloudflare custom-hostname flow. IP addresses, wildcard domains, credentials, ports, queries, and fragments are rejected. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $domain The custom domain as a hostname or URL.
     * @return \SellApp\Resource\SdkConnectCustomDomainResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function connect(
        string $domain,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkConnectCustomDomainResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'connectCustomDomain', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'domain' => $domain,
        ];
        \SellApp\Resource\SdkConnectCustomDomainRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/store/custom-domains',
            body: $body,
            options: $options,
        );
        return SdkConnectCustomDomainResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Retrieve a custom domain
     *
     * Retrieve a custom domain. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $customDomain The customDomain path parameter.
     * @return \SellApp\Resource\SdkGetCustomDomainResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $customDomain,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetCustomDomainResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getCustomDomain', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/store/custom-domains/' . rawurlencode((string) $customDomain),
            options: $options,
        );
        return SdkGetCustomDomainResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Disconnect a custom domain
     *
     * Disconnect a custom domain. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $customDomain The customDomain path parameter.
     * @return void
     * @throws \SellApp\Exception\SDKException
     */
    public function disconnect(
        int $customDomain,
        ?\SellApp\RequestOptions $options = null,
    ): void {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'disconnectCustomDomain', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $this->client->request(
            method: 'DELETE',
            path: 'v2/store/custom-domains/' . rawurlencode((string) $customDomain),
            options: $options,
        );
    }

    /**
     * Refresh custom domain status
     *
     * Ask Cloudflare to re-run custom-hostname validation and persist the latest DNS and SSL state. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $customDomain The customDomain path parameter.
     * @return \SellApp\Resource\SdkRefreshCustomDomainStatusResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function refresh(
        int $customDomain,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkRefreshCustomDomainStatusResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'refreshCustomDomainStatus', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/store/custom-domains/' . rawurlencode((string) $customDomain) . '/refresh',
            options: $options,
        );
        return SdkRefreshCustomDomainStatusResponseValue200ApplicationJson::fromArray($response);
    }
}
