<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListTicketsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkGetTicketResponseValue200ApplicationJson;
use SellApp\Resource\SdkUpdateTicketResponseValue200ApplicationJson;
use SellApp\Resource\SdkV2GetTicketResponseValue200ApplicationJson;
use SellApp\Resource\SearchTicketsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\V2ListTicketsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem;

class Tickets
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List all tickets
     *
     * List your store's support tickets, 15 per page by default.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListTicketsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listTickets', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/tickets',
            query: $query,
            modelClass: ListTicketsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve specific ticket
     *
     * Retrieve a support ticket by its ID.
     * @param int $ticket The ticket path parameter.
     * @return \SellApp\Resource\SdkGetTicketResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        int $ticket,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetTicketResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getTicket', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/tickets/' . rawurlencode((string) $ticket),
            options: $options,
        );
        return SdkGetTicketResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Search tickets
     *
     * Search tickets using JSON body filters, search terms, includes, and sort instructions.
     * @param array<\SellApp\Resource\SearchTicketsRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\SearchTicketsRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\SearchTicketsRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\SearchTicketsRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SearchTicketsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\SearchTicketsRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchTickets', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":false,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":true,"apiKeyUsesStore":true,"accessTokenRequiresStore":false},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v1/tickets/search',
            modelClass: SearchTicketsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * List all tickets
     *
     * List your store's support tickets, 15 per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $limit Number of items to return per page. Defaults to 15.
     * @param int|null $page Page number to return. Defaults to 1.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\V2ListTicketsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function v2ListTickets(
        ?int $limit = null,
        ?int $page = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2ListTickets', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'limit' => $limit,
            'page' => $page,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/tickets',
            query: $query,
            modelClass: V2ListTicketsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Search tickets
     *
     * Search tickets using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param array<\SellApp\Resource\V2SearchTicketsRequestApplicationJsonPropertyFiltersItem>|null $filters
     * @param array<\SellApp\Resource\V2SearchTicketsRequestApplicationJsonPropertySortItem>|null $sort
     * @param \SellApp\Resource\V2SearchTicketsRequestApplicationJsonPropertySearch|null $search
     * @param array<\SellApp\Resource\V2SearchTicketsRequestApplicationJsonPropertyIncludesItem>|null $includes
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function v2SearchTickets(
        ?array $filters = null,
        ?array $sort = null,
        ?\SellApp\Resource\V2SearchTicketsRequestApplicationJsonPropertySearch $search = null,
        ?array $includes = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2SearchTickets', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/tickets/search',
            modelClass: V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Retrieve specific ticket
     *
     * Retrieve a support ticket by its ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $ticket The ticket path parameter.
     * @return \SellApp\Resource\SdkV2GetTicketResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function v2GetTicket(
        int $ticket,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkV2GetTicketResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'v2GetTicket', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/tickets/' . rawurlencode((string) $ticket),
            options: $options,
        );
        return SdkV2GetTicketResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Close, reopen, or archive a ticket
     *
     * Change ticket status or archive state in the selected store. Requires the ticket API-key ability and store ticket permission. Send status OPEN to reopen or CLOSED to close; closing sends the existing customer notification only when the status changes. Send archived true to archive or false to restore. You may send both fields together; omitted fields stay unchanged. Use the same optional Idempotency-Key and identical body after a lost response. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int $ticket
     * @param \SellApp\Resource\SdkUpdateTicketRequestApplicationJsonStatus|null $status
     * @param bool|null $archived
     * @return \SellApp\Resource\SdkUpdateTicketResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function update(
        int $ticket,
        ?\SellApp\Resource\SdkUpdateTicketRequestApplicationJsonStatus $status = null,
        ?bool $archived = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkUpdateTicketResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(true, 'updateTicket', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'status' => $status?->value,
            'archived' => $archived,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkUpdateTicketRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/tickets/' . rawurlencode((string) $ticket),
            body: $body,
            options: $options,
        );
        return SdkUpdateTicketResponseValue200ApplicationJson::fromArray($response);
    }
}
