<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\SdkGetVariantDeliverableConfigurationResponseValue200ApplicationJson;
use SellApp\Resource\SdkReplaceVariantDeliverableConfigurationResponseValue200ApplicationJson;

class VariantDeliverables
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * Retrieve variant deliverable configuration
     *
     * Retrieve variant deliverable configuration. Requires the listing Sanctum ability. Returns delivery types and safe configuration for a variant in the authenticated store. Dynamic endpoint URLs and inventory data are not returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $product The product identifier or slug. The product must belong to the authenticated store.
     * @param int $variant The product variant identifier.
     * @return \SellApp\Resource\SdkGetVariantDeliverableConfigurationResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        string $product,
        int $variant,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetVariantDeliverableConfigurationResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getVariantDeliverableConfiguration', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/products/' . rawurlencode((string) $product) . '/variants/' . rawurlencode((string) $variant) . '/deliverable',
            options: $options,
        );
        return SdkGetVariantDeliverableConfigurationResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Replace variant deliverable configuration
     *
     * Replace variant deliverable configuration. Requires the listing Sanctum ability. Replaces this resource's delivery types atomically. Pass expected_updated_at from the product variant resource to reject stale updates with 422. TEXT, BOOKING, CREDITS, and BUNDLE must remain unchanged. Removing DOWNLOADABLE deletes managed files and folders after commit; removing a type clears its private configuration. Dynamic endpoints are write-only. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $product The product identifier or slug. The product must belong to the authenticated store.
     * @param int $variant The product variant identifier.
     * @param array<\SellApp\Resource\CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes> $types The complete type list. TEXT, BOOKING, CREDITS, and BUNDLE are owned by their dedicated resources and must remain unchanged here.
     * @param \DateTimeImmutable|null $expectedUpdatedAt Optional optimistic-concurrency snapshot from the deliverable resource's updated_at field. The request returns 422 if the variant changed after this timestamp was loaded.
     * @param \SellApp\Resource\ReplaceVariantDeliverableConfigurationRequestApplicationJsonPropertyData $data
     * @return \SellApp\Resource\SdkReplaceVariantDeliverableConfigurationResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function replace(
        string $product,
        int $variant,
        array $types,
        \SellApp\Resource\ReplaceVariantDeliverableConfigurationRequestApplicationJsonPropertyData $data,
        ?\DateTimeImmutable $expectedUpdatedAt = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkReplaceVariantDeliverableConfigurationResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'replaceVariantDeliverableConfiguration', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'types' => $types,
            'expected_updated_at' => $expectedUpdatedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'data' => $data,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkReplaceVariantDeliverableConfigurationRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/products/' . rawurlencode((string) $product) . '/variants/' . rawurlencode((string) $variant) . '/deliverable',
            body: $body,
            options: $options,
        );
        return SdkReplaceVariantDeliverableConfigurationResponseValue200ApplicationJson::fromArray($response);
    }
}
