<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp\Service;

use SellApp\Resource\ListWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem;
use SellApp\Resource\SdkCreateWebhookChannelResponseValue201ApplicationJson;
use SellApp\Resource\SdkGetWebhookChannelResponseValue200ApplicationJson;
use SellApp\Resource\SdkReplaceWebhookChannelResponseValue200ApplicationJson;
use SellApp\Resource\SdkRotateWebhookSigningSecretResponseValue200ApplicationJson;
use SellApp\Resource\SdkSendTestWebhookResponseValue200ApplicationJson;
use SellApp\Resource\SdkUpdateWebhookChannelResponseValue200ApplicationJson;
use SellApp\Resource\SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem;

class WebhookChannels
{
    public function __construct(
        private readonly \SellApp\HttpClient $client,
    ) {
    }

    public function withResponse(): \SellApp\RawResourceProxy
    {
        return $this->client->withResponse($this);
    }

    /**
     * List webhook channels
     *
     * Retrieve the authenticated store's outbound developer webhook destinations. Signing secrets and delivery headers are never included. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param int|null $page Page number. Defaults to 1.
     * @param int|null $limit Number of webhook channels to return per page. Defaults to 15.
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\ListWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function list(
        ?int $page = null,
        ?int $limit = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'listWebhookChannels', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $query = array_filter([
            'page' => $page,
            'limit' => $limit,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v2/webhook-channels',
            query: $query,
            modelClass: ListWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Create a webhook channel
     *
     * Create an outbound webhook destination with a stable UUID and an explicit event filter. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string|null $name Optional seller-facing reference name.
     * @param string $url Public HTTP or HTTPS destination. The same canonical URL cannot be configured twice for one store.
     * @param array<\SellApp\Resource\Event> $allowedNotifications Complete set of public webhook event names enabled for this destination.
     * @return \SellApp\Resource\SdkCreateWebhookChannelResponseValue201ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function create(
        string $url,
        array $allowedNotifications,
        ?string $name = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkCreateWebhookChannelResponseValue201ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'createWebhookChannel', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'name' => $name,
            'url' => $url,
            'allowed_notifications' => $allowedNotifications,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkCreateWebhookChannelRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/webhook-channels',
            body: $body,
            options: $options,
        );
        return SdkCreateWebhookChannelResponseValue201ApplicationJson::fromArray($response);
    }

    /**
     * Search webhook channels
     *
     * Search destinations by name or URL and optionally filter by a subscribed event. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param \SellApp\Resource\SearchWebhookChannelsRequestApplicationJsonPropertySearch|null $search
     * @param \SellApp\Resource\Event|null $event Public event name delivered in webhook payloads. SellApp maps it to the corresponding allowed_notifications filter.
     * @param int|null $page
     * @param int|null $limit
     * @return \SellApp\PaginatedResponse<\SellApp\Resource\SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem>
     * @throws \SellApp\Exception\SDKException
     */
    public function search(
        ?\SellApp\Resource\SearchWebhookChannelsRequestApplicationJsonPropertySearch $search = null,
        ?\SellApp\Resource\Event $event = null,
        ?int $page = null,
        ?int $limit = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\PaginatedResponse {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'searchWebhookChannels', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        return $this->client->requestPage(
            method: 'POST',
            path: 'v2/webhook-channels/search',
            modelClass: SearchWebhookChannelsResponseValue200ApplicationJsonPropertyDataItem::class,
            options: $options,
        );
    }

    /**
     * Rotate the webhook signing secret
     *
     * Replace the store-wide outbound webhook signing secret. The value is write-only and is never returned or written to delivery logs. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $signingSecret
     * @return \SellApp\Resource\SdkRotateWebhookSigningSecretResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function rotate(
        string $signingSecret,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkRotateWebhookSigningSecretResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'rotateWebhookSigningSecret', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'signing_secret' => $signingSecret,
        ];
        \SellApp\Resource\SdkRotateWebhookSigningSecretRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/webhook-channels/signing-secret',
            body: $body,
            options: $options,
        );
        return SdkRotateWebhookSigningSecretResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Retrieve a webhook channel
     *
     * Retrieve one outbound webhook destination by its stable UUID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $webhookChannel The stable webhook channel UUID.
     * @return \SellApp\Resource\SdkGetWebhookChannelResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function get(
        string $webhookChannel,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkGetWebhookChannelResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'getWebhookChannel', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $response = $this->client->request(
            method: 'GET',
            path: 'v2/webhook-channels/' . rawurlencode((string) $webhookChannel),
            options: $options,
        );
        return SdkGetWebhookChannelResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Replace a webhook channel
     *
     * Replace a destination with a complete representation. name, url, and allowed_notifications must all be present. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $webhookChannel The stable webhook channel UUID.
     * @param string|null $name Optional seller-facing reference name.
     * @param string $url Public HTTP or HTTPS destination. The same canonical URL cannot be configured twice for one store.
     * @param array<\SellApp\Resource\Event> $allowedNotifications Complete set of public webhook event names enabled for this destination.
     * @return \SellApp\Resource\SdkReplaceWebhookChannelResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function replace(
        string $webhookChannel,
        ?string $name,
        string $url,
        array $allowedNotifications,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkReplaceWebhookChannelResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'replaceWebhookChannel', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'name' => $name,
            'url' => $url,
            'allowed_notifications' => $allowedNotifications,
        ];
        \SellApp\Resource\SdkReplaceWebhookChannelRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PUT',
            path: 'v2/webhook-channels/' . rawurlencode((string) $webhookChannel),
            body: $body,
            options: $options,
        );
        return SdkReplaceWebhookChannelResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Update a webhook channel
     *
     * Partially update a destination. Supplying allowed_notifications replaces the complete event filter; omitted fields retain their current values. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $webhookChannel The stable webhook channel UUID.
     * @param string|null $name Optional seller-facing reference name.
     * @param string|null $url Public HTTP or HTTPS destination. The same canonical URL cannot be configured twice for one store.
     * @param array<\SellApp\Resource\Event>|null $allowedNotifications Complete set of public webhook event names enabled for this destination.
     * @return \SellApp\Resource\SdkUpdateWebhookChannelResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function update(
        string $webhookChannel,
        ?string $name = null,
        ?string $url = null,
        ?array $allowedNotifications = null,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkUpdateWebhookChannelResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'updateWebhookChannel', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = array_filter([
            'name' => $name,
            'url' => $url,
            'allowed_notifications' => $allowedNotifications,
        ], fn ($v) => $v !== null);
        \SellApp\Resource\SdkUpdateWebhookChannelRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v2/webhook-channels/' . rawurlencode((string) $webhookChannel),
            body: $body,
            options: $options,
        );
        return SdkUpdateWebhookChannelResponseValue200ApplicationJson::fromArray($response);
    }

    /**
     * Delete a webhook channel
     *
     * Delete a destination. Other channel UUIDs remain unchanged and the deleted UUID is not reassigned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $webhookChannel The stable webhook channel UUID.
     * @return void
     * @throws \SellApp\Exception\SDKException
     */
    public function delete(
        string $webhookChannel,
        ?\SellApp\RequestOptions $options = null,
    ): void {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'deleteWebhookChannel', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $this->client->request(
            method: 'DELETE',
            path: 'v2/webhook-channels/' . rawurlencode((string) $webhookChannel),
            options: $options,
        );
    }

    /**
     * Send a test webhook
     *
     * Synchronously send one mock delivery to the stored destination. `event` is the public delivery event name and the same name must already be enabled in `allowed_notifications`. The test payload uses the same top-level event/version contract as production. Test deliveries do not retry or follow redirects and never return response bodies or signing headers. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
     * @param string $webhookChannel The stable webhook channel UUID.
     * @param \SellApp\Resource\Event $event Public event name used by channel configuration, search, tests, and delivered webhook payloads.
     * @return \SellApp\Resource\SdkSendTestWebhookResponseValue200ApplicationJson
     * @throws \SellApp\Exception\SDKException
     */
    public function send(
        string $webhookChannel,
        \SellApp\Resource\Event $event,
        ?\SellApp\RequestOptions $options = null,
    ): \SellApp\Resource\SdkSendTestWebhookResponseValue200ApplicationJson {
        $options = ($options ?? new \SellApp\RequestOptions())->forOperation(false, 'sendTestWebhook', null, json_decode('{"auth":{"alternatives":[[{"schemeName":"bearerAuth","scopes":[]}],[{"schemeName":"oauthAccessToken","scopes":["admin"]},{"schemeName":"storeAuth","scopes":[]}]],"anonymous":false,"apiKey":true,"accessToken":true,"customerSession":false,"browserSession":false,"clientBasic":false,"apiKeyRequiresStore":false,"apiKeyUsesStore":true,"accessTokenRequiresStore":true},"noRetry":false,"textResponse":false}', true, 512, JSON_THROW_ON_ERROR));
        $body = [
            'event' => $event->value,
        ];
        \SellApp\Resource\SdkSendTestWebhookRequestApplicationJson::validate($body, 'request');
        $response = $this->client->request(
            method: 'POST',
            path: 'v2/webhook-channels/' . rawurlencode((string) $webhookChannel) . '/test',
            body: $body,
            options: $options,
        );
        return SdkSendTestWebhookResponseValue200ApplicationJson::fromArray($response);
    }
}
