<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace SellApp;
/** @template T */
final class RawResponse { /** @param T $data */ public function __construct(public readonly mixed $data, public readonly int $status, public readonly array $headers, public readonly ?string $requestId = null) {} }
/** @internal Operation-level raw-response facade. */
final class RawResourceProxy { public function __construct(private readonly object $resource, private readonly HttpClient $client) {} public function __call(string $name,array $arguments): RawResponse { return $this->client->captureResponse(fn()=> $this->resource->{$name}(...$arguments)); } }
